
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Verification
 * 
 */
export type Verification = Prisma.VerificationModel
/**
 * Model Skill
 * 
 */
export type Skill = Prisma.SkillModel
/**
 * Model SkillRelation
 * 
 */
export type SkillRelation = Prisma.SkillRelationModel
/**
 * Model Assessment
 * 
 */
export type Assessment = Prisma.AssessmentModel
/**
 * Model AssessmentResult
 * 
 */
export type AssessmentResult = Prisma.AssessmentResultModel
/**
 * Model Resource
 * 
 */
export type Resource = Prisma.ResourceModel
/**
 * Model Evidence
 * 
 */
export type Evidence = Prisma.EvidenceModel
