
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Session'
export type * from './models/Account'
export type * from './models/Verification'
export type * from './models/Skill'
export type * from './models/SkillRelation'
export type * from './models/Assessment'
export type * from './models/AssessmentResult'
export type * from './models/Resource'
export type * from './models/Evidence'
export type * from './commonInputTypes'