
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AssessmentResult` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AssessmentResult
 * 
 */
export type AssessmentResultModel = runtime.Types.Result.DefaultSelection<Prisma.$AssessmentResultPayload>

export type AggregateAssessmentResult = {
  _count: AssessmentResultCountAggregateOutputType | null
  _avg: AssessmentResultAvgAggregateOutputType | null
  _sum: AssessmentResultSumAggregateOutputType | null
  _min: AssessmentResultMinAggregateOutputType | null
  _max: AssessmentResultMaxAggregateOutputType | null
}

export type AssessmentResultAvgAggregateOutputType = {
  level: number | null
  confidence: number | null
}

export type AssessmentResultSumAggregateOutputType = {
  level: number | null
  confidence: number | null
}

export type AssessmentResultMinAggregateOutputType = {
  id: string | null
  assessmentId: string | null
  skillId: string | null
  level: number | null
  confidence: number | null
  notes: string | null
  createdAt: Date | null
}

export type AssessmentResultMaxAggregateOutputType = {
  id: string | null
  assessmentId: string | null
  skillId: string | null
  level: number | null
  confidence: number | null
  notes: string | null
  createdAt: Date | null
}

export type AssessmentResultCountAggregateOutputType = {
  id: number
  assessmentId: number
  skillId: number
  level: number
  confidence: number
  notes: number
  rawAIOutput: number
  createdAt: number
  _all: number
}


export type AssessmentResultAvgAggregateInputType = {
  level?: true
  confidence?: true
}

export type AssessmentResultSumAggregateInputType = {
  level?: true
  confidence?: true
}

export type AssessmentResultMinAggregateInputType = {
  id?: true
  assessmentId?: true
  skillId?: true
  level?: true
  confidence?: true
  notes?: true
  createdAt?: true
}

export type AssessmentResultMaxAggregateInputType = {
  id?: true
  assessmentId?: true
  skillId?: true
  level?: true
  confidence?: true
  notes?: true
  createdAt?: true
}

export type AssessmentResultCountAggregateInputType = {
  id?: true
  assessmentId?: true
  skillId?: true
  level?: true
  confidence?: true
  notes?: true
  rawAIOutput?: true
  createdAt?: true
  _all?: true
}

export type AssessmentResultAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssessmentResult to aggregate.
   */
  where?: Prisma.AssessmentResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssessmentResults to fetch.
   */
  orderBy?: Prisma.AssessmentResultOrderByWithRelationInput | Prisma.AssessmentResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssessmentResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssessmentResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssessmentResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AssessmentResults
  **/
  _count?: true | AssessmentResultCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AssessmentResultAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AssessmentResultSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssessmentResultMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssessmentResultMaxAggregateInputType
}

export type GetAssessmentResultAggregateType<T extends AssessmentResultAggregateArgs> = {
      [P in keyof T & keyof AggregateAssessmentResult]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssessmentResult[P]>
    : Prisma.GetScalarType<T[P], AggregateAssessmentResult[P]>
}




export type AssessmentResultGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssessmentResultWhereInput
  orderBy?: Prisma.AssessmentResultOrderByWithAggregationInput | Prisma.AssessmentResultOrderByWithAggregationInput[]
  by: Prisma.AssessmentResultScalarFieldEnum[] | Prisma.AssessmentResultScalarFieldEnum
  having?: Prisma.AssessmentResultScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssessmentResultCountAggregateInputType | true
  _avg?: AssessmentResultAvgAggregateInputType
  _sum?: AssessmentResultSumAggregateInputType
  _min?: AssessmentResultMinAggregateInputType
  _max?: AssessmentResultMaxAggregateInputType
}

export type AssessmentResultGroupByOutputType = {
  id: string
  assessmentId: string
  skillId: string
  level: number
  confidence: number
  notes: string | null
  rawAIOutput: runtime.JsonValue | null
  createdAt: Date
  _count: AssessmentResultCountAggregateOutputType | null
  _avg: AssessmentResultAvgAggregateOutputType | null
  _sum: AssessmentResultSumAggregateOutputType | null
  _min: AssessmentResultMinAggregateOutputType | null
  _max: AssessmentResultMaxAggregateOutputType | null
}

type GetAssessmentResultGroupByPayload<T extends AssessmentResultGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssessmentResultGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssessmentResultGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssessmentResultGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssessmentResultGroupByOutputType[P]>
      }
    >
  >



export type AssessmentResultWhereInput = {
  AND?: Prisma.AssessmentResultWhereInput | Prisma.AssessmentResultWhereInput[]
  OR?: Prisma.AssessmentResultWhereInput[]
  NOT?: Prisma.AssessmentResultWhereInput | Prisma.AssessmentResultWhereInput[]
  id?: Prisma.StringFilter<"AssessmentResult"> | string
  assessmentId?: Prisma.StringFilter<"AssessmentResult"> | string
  skillId?: Prisma.StringFilter<"AssessmentResult"> | string
  level?: Prisma.IntFilter<"AssessmentResult"> | number
  confidence?: Prisma.FloatFilter<"AssessmentResult"> | number
  notes?: Prisma.StringNullableFilter<"AssessmentResult"> | string | null
  rawAIOutput?: Prisma.JsonNullableFilter<"AssessmentResult">
  createdAt?: Prisma.DateTimeFilter<"AssessmentResult"> | Date | string
  assessment?: Prisma.XOR<Prisma.AssessmentScalarRelationFilter, Prisma.AssessmentWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}

export type AssessmentResultOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  level?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  rawAIOutput?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  assessment?: Prisma.AssessmentOrderByWithRelationInput
  skill?: Prisma.SkillOrderByWithRelationInput
}

export type AssessmentResultWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  assessmentId_skillId?: Prisma.AssessmentResultAssessmentIdSkillIdCompoundUniqueInput
  AND?: Prisma.AssessmentResultWhereInput | Prisma.AssessmentResultWhereInput[]
  OR?: Prisma.AssessmentResultWhereInput[]
  NOT?: Prisma.AssessmentResultWhereInput | Prisma.AssessmentResultWhereInput[]
  assessmentId?: Prisma.StringFilter<"AssessmentResult"> | string
  skillId?: Prisma.StringFilter<"AssessmentResult"> | string
  level?: Prisma.IntFilter<"AssessmentResult"> | number
  confidence?: Prisma.FloatFilter<"AssessmentResult"> | number
  notes?: Prisma.StringNullableFilter<"AssessmentResult"> | string | null
  rawAIOutput?: Prisma.JsonNullableFilter<"AssessmentResult">
  createdAt?: Prisma.DateTimeFilter<"AssessmentResult"> | Date | string
  assessment?: Prisma.XOR<Prisma.AssessmentScalarRelationFilter, Prisma.AssessmentWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}, "id" | "assessmentId_skillId">

export type AssessmentResultOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  level?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  rawAIOutput?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AssessmentResultCountOrderByAggregateInput
  _avg?: Prisma.AssessmentResultAvgOrderByAggregateInput
  _max?: Prisma.AssessmentResultMaxOrderByAggregateInput
  _min?: Prisma.AssessmentResultMinOrderByAggregateInput
  _sum?: Prisma.AssessmentResultSumOrderByAggregateInput
}

export type AssessmentResultScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssessmentResultScalarWhereWithAggregatesInput | Prisma.AssessmentResultScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssessmentResultScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssessmentResultScalarWhereWithAggregatesInput | Prisma.AssessmentResultScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AssessmentResult"> | string
  assessmentId?: Prisma.StringWithAggregatesFilter<"AssessmentResult"> | string
  skillId?: Prisma.StringWithAggregatesFilter<"AssessmentResult"> | string
  level?: Prisma.IntWithAggregatesFilter<"AssessmentResult"> | number
  confidence?: Prisma.FloatWithAggregatesFilter<"AssessmentResult"> | number
  notes?: Prisma.StringNullableWithAggregatesFilter<"AssessmentResult"> | string | null
  rawAIOutput?: Prisma.JsonNullableWithAggregatesFilter<"AssessmentResult">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AssessmentResult"> | Date | string
}

export type AssessmentResultCreateInput = {
  id?: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  assessment: Prisma.AssessmentCreateNestedOneWithoutResultsInput
  skill: Prisma.SkillCreateNestedOneWithoutAssessmentResultsInput
}

export type AssessmentResultUncheckedCreateInput = {
  id?: string
  assessmentId: string
  skillId: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AssessmentResultUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assessment?: Prisma.AssessmentUpdateOneRequiredWithoutResultsNestedInput
  skill?: Prisma.SkillUpdateOneRequiredWithoutAssessmentResultsNestedInput
}

export type AssessmentResultUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assessmentId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentResultCreateManyInput = {
  id?: string
  assessmentId: string
  skillId: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AssessmentResultUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentResultUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assessmentId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentResultListRelationFilter = {
  every?: Prisma.AssessmentResultWhereInput
  some?: Prisma.AssessmentResultWhereInput
  none?: Prisma.AssessmentResultWhereInput
}

export type AssessmentResultOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssessmentResultAssessmentIdSkillIdCompoundUniqueInput = {
  assessmentId: string
  skillId: string
}

export type AssessmentResultCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  level?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  rawAIOutput?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssessmentResultAvgOrderByAggregateInput = {
  level?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
}

export type AssessmentResultMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  level?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssessmentResultMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  assessmentId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  level?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AssessmentResultSumOrderByAggregateInput = {
  level?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
}

export type AssessmentResultCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.AssessmentResultCreateWithoutSkillInput, Prisma.AssessmentResultUncheckedCreateWithoutSkillInput> | Prisma.AssessmentResultCreateWithoutSkillInput[] | Prisma.AssessmentResultUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.AssessmentResultCreateOrConnectWithoutSkillInput | Prisma.AssessmentResultCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.AssessmentResultCreateManySkillInputEnvelope
  connect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
}

export type AssessmentResultUncheckedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.AssessmentResultCreateWithoutSkillInput, Prisma.AssessmentResultUncheckedCreateWithoutSkillInput> | Prisma.AssessmentResultCreateWithoutSkillInput[] | Prisma.AssessmentResultUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.AssessmentResultCreateOrConnectWithoutSkillInput | Prisma.AssessmentResultCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.AssessmentResultCreateManySkillInputEnvelope
  connect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
}

export type AssessmentResultUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentResultCreateWithoutSkillInput, Prisma.AssessmentResultUncheckedCreateWithoutSkillInput> | Prisma.AssessmentResultCreateWithoutSkillInput[] | Prisma.AssessmentResultUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.AssessmentResultCreateOrConnectWithoutSkillInput | Prisma.AssessmentResultCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.AssessmentResultUpsertWithWhereUniqueWithoutSkillInput | Prisma.AssessmentResultUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.AssessmentResultCreateManySkillInputEnvelope
  set?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  disconnect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  delete?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  connect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  update?: Prisma.AssessmentResultUpdateWithWhereUniqueWithoutSkillInput | Prisma.AssessmentResultUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.AssessmentResultUpdateManyWithWhereWithoutSkillInput | Prisma.AssessmentResultUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.AssessmentResultScalarWhereInput | Prisma.AssessmentResultScalarWhereInput[]
}

export type AssessmentResultUncheckedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentResultCreateWithoutSkillInput, Prisma.AssessmentResultUncheckedCreateWithoutSkillInput> | Prisma.AssessmentResultCreateWithoutSkillInput[] | Prisma.AssessmentResultUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.AssessmentResultCreateOrConnectWithoutSkillInput | Prisma.AssessmentResultCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.AssessmentResultUpsertWithWhereUniqueWithoutSkillInput | Prisma.AssessmentResultUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.AssessmentResultCreateManySkillInputEnvelope
  set?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  disconnect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  delete?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  connect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  update?: Prisma.AssessmentResultUpdateWithWhereUniqueWithoutSkillInput | Prisma.AssessmentResultUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.AssessmentResultUpdateManyWithWhereWithoutSkillInput | Prisma.AssessmentResultUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.AssessmentResultScalarWhereInput | Prisma.AssessmentResultScalarWhereInput[]
}

export type AssessmentResultCreateNestedManyWithoutAssessmentInput = {
  create?: Prisma.XOR<Prisma.AssessmentResultCreateWithoutAssessmentInput, Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput> | Prisma.AssessmentResultCreateWithoutAssessmentInput[] | Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput[]
  connectOrCreate?: Prisma.AssessmentResultCreateOrConnectWithoutAssessmentInput | Prisma.AssessmentResultCreateOrConnectWithoutAssessmentInput[]
  createMany?: Prisma.AssessmentResultCreateManyAssessmentInputEnvelope
  connect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
}

export type AssessmentResultUncheckedCreateNestedManyWithoutAssessmentInput = {
  create?: Prisma.XOR<Prisma.AssessmentResultCreateWithoutAssessmentInput, Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput> | Prisma.AssessmentResultCreateWithoutAssessmentInput[] | Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput[]
  connectOrCreate?: Prisma.AssessmentResultCreateOrConnectWithoutAssessmentInput | Prisma.AssessmentResultCreateOrConnectWithoutAssessmentInput[]
  createMany?: Prisma.AssessmentResultCreateManyAssessmentInputEnvelope
  connect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
}

export type AssessmentResultUpdateManyWithoutAssessmentNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentResultCreateWithoutAssessmentInput, Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput> | Prisma.AssessmentResultCreateWithoutAssessmentInput[] | Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput[]
  connectOrCreate?: Prisma.AssessmentResultCreateOrConnectWithoutAssessmentInput | Prisma.AssessmentResultCreateOrConnectWithoutAssessmentInput[]
  upsert?: Prisma.AssessmentResultUpsertWithWhereUniqueWithoutAssessmentInput | Prisma.AssessmentResultUpsertWithWhereUniqueWithoutAssessmentInput[]
  createMany?: Prisma.AssessmentResultCreateManyAssessmentInputEnvelope
  set?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  disconnect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  delete?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  connect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  update?: Prisma.AssessmentResultUpdateWithWhereUniqueWithoutAssessmentInput | Prisma.AssessmentResultUpdateWithWhereUniqueWithoutAssessmentInput[]
  updateMany?: Prisma.AssessmentResultUpdateManyWithWhereWithoutAssessmentInput | Prisma.AssessmentResultUpdateManyWithWhereWithoutAssessmentInput[]
  deleteMany?: Prisma.AssessmentResultScalarWhereInput | Prisma.AssessmentResultScalarWhereInput[]
}

export type AssessmentResultUncheckedUpdateManyWithoutAssessmentNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentResultCreateWithoutAssessmentInput, Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput> | Prisma.AssessmentResultCreateWithoutAssessmentInput[] | Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput[]
  connectOrCreate?: Prisma.AssessmentResultCreateOrConnectWithoutAssessmentInput | Prisma.AssessmentResultCreateOrConnectWithoutAssessmentInput[]
  upsert?: Prisma.AssessmentResultUpsertWithWhereUniqueWithoutAssessmentInput | Prisma.AssessmentResultUpsertWithWhereUniqueWithoutAssessmentInput[]
  createMany?: Prisma.AssessmentResultCreateManyAssessmentInputEnvelope
  set?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  disconnect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  delete?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  connect?: Prisma.AssessmentResultWhereUniqueInput | Prisma.AssessmentResultWhereUniqueInput[]
  update?: Prisma.AssessmentResultUpdateWithWhereUniqueWithoutAssessmentInput | Prisma.AssessmentResultUpdateWithWhereUniqueWithoutAssessmentInput[]
  updateMany?: Prisma.AssessmentResultUpdateManyWithWhereWithoutAssessmentInput | Prisma.AssessmentResultUpdateManyWithWhereWithoutAssessmentInput[]
  deleteMany?: Prisma.AssessmentResultScalarWhereInput | Prisma.AssessmentResultScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type AssessmentResultCreateWithoutSkillInput = {
  id?: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  assessment: Prisma.AssessmentCreateNestedOneWithoutResultsInput
}

export type AssessmentResultUncheckedCreateWithoutSkillInput = {
  id?: string
  assessmentId: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AssessmentResultCreateOrConnectWithoutSkillInput = {
  where: Prisma.AssessmentResultWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentResultCreateWithoutSkillInput, Prisma.AssessmentResultUncheckedCreateWithoutSkillInput>
}

export type AssessmentResultCreateManySkillInputEnvelope = {
  data: Prisma.AssessmentResultCreateManySkillInput | Prisma.AssessmentResultCreateManySkillInput[]
  skipDuplicates?: boolean
}

export type AssessmentResultUpsertWithWhereUniqueWithoutSkillInput = {
  where: Prisma.AssessmentResultWhereUniqueInput
  update: Prisma.XOR<Prisma.AssessmentResultUpdateWithoutSkillInput, Prisma.AssessmentResultUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.AssessmentResultCreateWithoutSkillInput, Prisma.AssessmentResultUncheckedCreateWithoutSkillInput>
}

export type AssessmentResultUpdateWithWhereUniqueWithoutSkillInput = {
  where: Prisma.AssessmentResultWhereUniqueInput
  data: Prisma.XOR<Prisma.AssessmentResultUpdateWithoutSkillInput, Prisma.AssessmentResultUncheckedUpdateWithoutSkillInput>
}

export type AssessmentResultUpdateManyWithWhereWithoutSkillInput = {
  where: Prisma.AssessmentResultScalarWhereInput
  data: Prisma.XOR<Prisma.AssessmentResultUpdateManyMutationInput, Prisma.AssessmentResultUncheckedUpdateManyWithoutSkillInput>
}

export type AssessmentResultScalarWhereInput = {
  AND?: Prisma.AssessmentResultScalarWhereInput | Prisma.AssessmentResultScalarWhereInput[]
  OR?: Prisma.AssessmentResultScalarWhereInput[]
  NOT?: Prisma.AssessmentResultScalarWhereInput | Prisma.AssessmentResultScalarWhereInput[]
  id?: Prisma.StringFilter<"AssessmentResult"> | string
  assessmentId?: Prisma.StringFilter<"AssessmentResult"> | string
  skillId?: Prisma.StringFilter<"AssessmentResult"> | string
  level?: Prisma.IntFilter<"AssessmentResult"> | number
  confidence?: Prisma.FloatFilter<"AssessmentResult"> | number
  notes?: Prisma.StringNullableFilter<"AssessmentResult"> | string | null
  rawAIOutput?: Prisma.JsonNullableFilter<"AssessmentResult">
  createdAt?: Prisma.DateTimeFilter<"AssessmentResult"> | Date | string
}

export type AssessmentResultCreateWithoutAssessmentInput = {
  id?: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  skill: Prisma.SkillCreateNestedOneWithoutAssessmentResultsInput
}

export type AssessmentResultUncheckedCreateWithoutAssessmentInput = {
  id?: string
  skillId: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AssessmentResultCreateOrConnectWithoutAssessmentInput = {
  where: Prisma.AssessmentResultWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentResultCreateWithoutAssessmentInput, Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput>
}

export type AssessmentResultCreateManyAssessmentInputEnvelope = {
  data: Prisma.AssessmentResultCreateManyAssessmentInput | Prisma.AssessmentResultCreateManyAssessmentInput[]
  skipDuplicates?: boolean
}

export type AssessmentResultUpsertWithWhereUniqueWithoutAssessmentInput = {
  where: Prisma.AssessmentResultWhereUniqueInput
  update: Prisma.XOR<Prisma.AssessmentResultUpdateWithoutAssessmentInput, Prisma.AssessmentResultUncheckedUpdateWithoutAssessmentInput>
  create: Prisma.XOR<Prisma.AssessmentResultCreateWithoutAssessmentInput, Prisma.AssessmentResultUncheckedCreateWithoutAssessmentInput>
}

export type AssessmentResultUpdateWithWhereUniqueWithoutAssessmentInput = {
  where: Prisma.AssessmentResultWhereUniqueInput
  data: Prisma.XOR<Prisma.AssessmentResultUpdateWithoutAssessmentInput, Prisma.AssessmentResultUncheckedUpdateWithoutAssessmentInput>
}

export type AssessmentResultUpdateManyWithWhereWithoutAssessmentInput = {
  where: Prisma.AssessmentResultScalarWhereInput
  data: Prisma.XOR<Prisma.AssessmentResultUpdateManyMutationInput, Prisma.AssessmentResultUncheckedUpdateManyWithoutAssessmentInput>
}

export type AssessmentResultCreateManySkillInput = {
  id?: string
  assessmentId: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AssessmentResultUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  assessment?: Prisma.AssessmentUpdateOneRequiredWithoutResultsNestedInput
}

export type AssessmentResultUncheckedUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assessmentId?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentResultUncheckedUpdateManyWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assessmentId?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentResultCreateManyAssessmentInput = {
  id?: string
  skillId: string
  level: number
  confidence: number
  notes?: string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type AssessmentResultUpdateWithoutAssessmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  skill?: Prisma.SkillUpdateOneRequiredWithoutAssessmentResultsNestedInput
}

export type AssessmentResultUncheckedUpdateWithoutAssessmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssessmentResultUncheckedUpdateManyWithoutAssessmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  confidence?: Prisma.FloatFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawAIOutput?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AssessmentResultSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assessmentId?: boolean
  skillId?: boolean
  level?: boolean
  confidence?: boolean
  notes?: boolean
  rawAIOutput?: boolean
  createdAt?: boolean
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessmentResult"]>

export type AssessmentResultSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assessmentId?: boolean
  skillId?: boolean
  level?: boolean
  confidence?: boolean
  notes?: boolean
  rawAIOutput?: boolean
  createdAt?: boolean
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessmentResult"]>

export type AssessmentResultSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  assessmentId?: boolean
  skillId?: boolean
  level?: boolean
  confidence?: boolean
  notes?: boolean
  rawAIOutput?: boolean
  createdAt?: boolean
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessmentResult"]>

export type AssessmentResultSelectScalar = {
  id?: boolean
  assessmentId?: boolean
  skillId?: boolean
  level?: boolean
  confidence?: boolean
  notes?: boolean
  rawAIOutput?: boolean
  createdAt?: boolean
}

export type AssessmentResultOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "assessmentId" | "skillId" | "level" | "confidence" | "notes" | "rawAIOutput" | "createdAt", ExtArgs["result"]["assessmentResult"]>
export type AssessmentResultInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type AssessmentResultIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type AssessmentResultIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  assessment?: boolean | Prisma.AssessmentDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}

export type $AssessmentResultPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AssessmentResult"
  objects: {
    assessment: Prisma.$AssessmentPayload<ExtArgs>
    skill: Prisma.$SkillPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    assessmentId: string
    skillId: string
    level: number
    confidence: number
    notes: string | null
    rawAIOutput: runtime.JsonValue | null
    createdAt: Date
  }, ExtArgs["result"]["assessmentResult"]>
  composites: {}
}

export type AssessmentResultGetPayload<S extends boolean | null | undefined | AssessmentResultDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload, S>

export type AssessmentResultCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssessmentResultFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssessmentResultCountAggregateInputType | true
  }

export interface AssessmentResultDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AssessmentResult'], meta: { name: 'AssessmentResult' } }
  /**
   * Find zero or one AssessmentResult that matches the filter.
   * @param {AssessmentResultFindUniqueArgs} args - Arguments to find a AssessmentResult
   * @example
   * // Get one AssessmentResult
   * const assessmentResult = await prisma.assessmentResult.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssessmentResultFindUniqueArgs>(args: Prisma.SelectSubset<T, AssessmentResultFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssessmentResultClient<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AssessmentResult that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssessmentResultFindUniqueOrThrowArgs} args - Arguments to find a AssessmentResult
   * @example
   * // Get one AssessmentResult
   * const assessmentResult = await prisma.assessmentResult.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssessmentResultFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssessmentResultFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssessmentResultClient<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssessmentResult that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentResultFindFirstArgs} args - Arguments to find a AssessmentResult
   * @example
   * // Get one AssessmentResult
   * const assessmentResult = await prisma.assessmentResult.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssessmentResultFindFirstArgs>(args?: Prisma.SelectSubset<T, AssessmentResultFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssessmentResultClient<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssessmentResult that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentResultFindFirstOrThrowArgs} args - Arguments to find a AssessmentResult
   * @example
   * // Get one AssessmentResult
   * const assessmentResult = await prisma.assessmentResult.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssessmentResultFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssessmentResultFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssessmentResultClient<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AssessmentResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentResultFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AssessmentResults
   * const assessmentResults = await prisma.assessmentResult.findMany()
   * 
   * // Get first 10 AssessmentResults
   * const assessmentResults = await prisma.assessmentResult.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assessmentResultWithIdOnly = await prisma.assessmentResult.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AssessmentResultFindManyArgs>(args?: Prisma.SelectSubset<T, AssessmentResultFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AssessmentResult.
   * @param {AssessmentResultCreateArgs} args - Arguments to create a AssessmentResult.
   * @example
   * // Create one AssessmentResult
   * const AssessmentResult = await prisma.assessmentResult.create({
   *   data: {
   *     // ... data to create a AssessmentResult
   *   }
   * })
   * 
   */
  create<T extends AssessmentResultCreateArgs>(args: Prisma.SelectSubset<T, AssessmentResultCreateArgs<ExtArgs>>): Prisma.Prisma__AssessmentResultClient<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AssessmentResults.
   * @param {AssessmentResultCreateManyArgs} args - Arguments to create many AssessmentResults.
   * @example
   * // Create many AssessmentResults
   * const assessmentResult = await prisma.assessmentResult.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssessmentResultCreateManyArgs>(args?: Prisma.SelectSubset<T, AssessmentResultCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AssessmentResults and returns the data saved in the database.
   * @param {AssessmentResultCreateManyAndReturnArgs} args - Arguments to create many AssessmentResults.
   * @example
   * // Create many AssessmentResults
   * const assessmentResult = await prisma.assessmentResult.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AssessmentResults and only return the `id`
   * const assessmentResultWithIdOnly = await prisma.assessmentResult.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssessmentResultCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssessmentResultCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AssessmentResult.
   * @param {AssessmentResultDeleteArgs} args - Arguments to delete one AssessmentResult.
   * @example
   * // Delete one AssessmentResult
   * const AssessmentResult = await prisma.assessmentResult.delete({
   *   where: {
   *     // ... filter to delete one AssessmentResult
   *   }
   * })
   * 
   */
  delete<T extends AssessmentResultDeleteArgs>(args: Prisma.SelectSubset<T, AssessmentResultDeleteArgs<ExtArgs>>): Prisma.Prisma__AssessmentResultClient<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AssessmentResult.
   * @param {AssessmentResultUpdateArgs} args - Arguments to update one AssessmentResult.
   * @example
   * // Update one AssessmentResult
   * const assessmentResult = await prisma.assessmentResult.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssessmentResultUpdateArgs>(args: Prisma.SelectSubset<T, AssessmentResultUpdateArgs<ExtArgs>>): Prisma.Prisma__AssessmentResultClient<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AssessmentResults.
   * @param {AssessmentResultDeleteManyArgs} args - Arguments to filter AssessmentResults to delete.
   * @example
   * // Delete a few AssessmentResults
   * const { count } = await prisma.assessmentResult.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssessmentResultDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssessmentResultDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssessmentResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentResultUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AssessmentResults
   * const assessmentResult = await prisma.assessmentResult.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssessmentResultUpdateManyArgs>(args: Prisma.SelectSubset<T, AssessmentResultUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssessmentResults and returns the data updated in the database.
   * @param {AssessmentResultUpdateManyAndReturnArgs} args - Arguments to update many AssessmentResults.
   * @example
   * // Update many AssessmentResults
   * const assessmentResult = await prisma.assessmentResult.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AssessmentResults and only return the `id`
   * const assessmentResultWithIdOnly = await prisma.assessmentResult.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssessmentResultUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssessmentResultUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AssessmentResult.
   * @param {AssessmentResultUpsertArgs} args - Arguments to update or create a AssessmentResult.
   * @example
   * // Update or create a AssessmentResult
   * const assessmentResult = await prisma.assessmentResult.upsert({
   *   create: {
   *     // ... data to create a AssessmentResult
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AssessmentResult we want to update
   *   }
   * })
   */
  upsert<T extends AssessmentResultUpsertArgs>(args: Prisma.SelectSubset<T, AssessmentResultUpsertArgs<ExtArgs>>): Prisma.Prisma__AssessmentResultClient<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AssessmentResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentResultCountArgs} args - Arguments to filter AssessmentResults to count.
   * @example
   * // Count the number of AssessmentResults
   * const count = await prisma.assessmentResult.count({
   *   where: {
   *     // ... the filter for the AssessmentResults we want to count
   *   }
   * })
  **/
  count<T extends AssessmentResultCountArgs>(
    args?: Prisma.Subset<T, AssessmentResultCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssessmentResultCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AssessmentResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentResultAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssessmentResultAggregateArgs>(args: Prisma.Subset<T, AssessmentResultAggregateArgs>): Prisma.PrismaPromise<GetAssessmentResultAggregateType<T>>

  /**
   * Group by AssessmentResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentResultGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssessmentResultGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssessmentResultGroupByArgs['orderBy'] }
      : { orderBy?: AssessmentResultGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssessmentResultGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssessmentResultGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AssessmentResult model
 */
readonly fields: AssessmentResultFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AssessmentResult.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssessmentResultClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  assessment<T extends Prisma.AssessmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AssessmentDefaultArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  skill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AssessmentResult model
 */
export interface AssessmentResultFieldRefs {
  readonly id: Prisma.FieldRef<"AssessmentResult", 'String'>
  readonly assessmentId: Prisma.FieldRef<"AssessmentResult", 'String'>
  readonly skillId: Prisma.FieldRef<"AssessmentResult", 'String'>
  readonly level: Prisma.FieldRef<"AssessmentResult", 'Int'>
  readonly confidence: Prisma.FieldRef<"AssessmentResult", 'Float'>
  readonly notes: Prisma.FieldRef<"AssessmentResult", 'String'>
  readonly rawAIOutput: Prisma.FieldRef<"AssessmentResult", 'Json'>
  readonly createdAt: Prisma.FieldRef<"AssessmentResult", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AssessmentResult findUnique
 */
export type AssessmentResultFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentResult to fetch.
   */
  where: Prisma.AssessmentResultWhereUniqueInput
}

/**
 * AssessmentResult findUniqueOrThrow
 */
export type AssessmentResultFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentResult to fetch.
   */
  where: Prisma.AssessmentResultWhereUniqueInput
}

/**
 * AssessmentResult findFirst
 */
export type AssessmentResultFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentResult to fetch.
   */
  where?: Prisma.AssessmentResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssessmentResults to fetch.
   */
  orderBy?: Prisma.AssessmentResultOrderByWithRelationInput | Prisma.AssessmentResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssessmentResults.
   */
  cursor?: Prisma.AssessmentResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssessmentResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssessmentResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssessmentResults.
   */
  distinct?: Prisma.AssessmentResultScalarFieldEnum | Prisma.AssessmentResultScalarFieldEnum[]
}

/**
 * AssessmentResult findFirstOrThrow
 */
export type AssessmentResultFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentResult to fetch.
   */
  where?: Prisma.AssessmentResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssessmentResults to fetch.
   */
  orderBy?: Prisma.AssessmentResultOrderByWithRelationInput | Prisma.AssessmentResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssessmentResults.
   */
  cursor?: Prisma.AssessmentResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssessmentResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssessmentResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssessmentResults.
   */
  distinct?: Prisma.AssessmentResultScalarFieldEnum | Prisma.AssessmentResultScalarFieldEnum[]
}

/**
 * AssessmentResult findMany
 */
export type AssessmentResultFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * Filter, which AssessmentResults to fetch.
   */
  where?: Prisma.AssessmentResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssessmentResults to fetch.
   */
  orderBy?: Prisma.AssessmentResultOrderByWithRelationInput | Prisma.AssessmentResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AssessmentResults.
   */
  cursor?: Prisma.AssessmentResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssessmentResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssessmentResults.
   */
  skip?: number
  distinct?: Prisma.AssessmentResultScalarFieldEnum | Prisma.AssessmentResultScalarFieldEnum[]
}

/**
 * AssessmentResult create
 */
export type AssessmentResultCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * The data needed to create a AssessmentResult.
   */
  data: Prisma.XOR<Prisma.AssessmentResultCreateInput, Prisma.AssessmentResultUncheckedCreateInput>
}

/**
 * AssessmentResult createMany
 */
export type AssessmentResultCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AssessmentResults.
   */
  data: Prisma.AssessmentResultCreateManyInput | Prisma.AssessmentResultCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AssessmentResult createManyAndReturn
 */
export type AssessmentResultCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * The data used to create many AssessmentResults.
   */
  data: Prisma.AssessmentResultCreateManyInput | Prisma.AssessmentResultCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AssessmentResult update
 */
export type AssessmentResultUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * The data needed to update a AssessmentResult.
   */
  data: Prisma.XOR<Prisma.AssessmentResultUpdateInput, Prisma.AssessmentResultUncheckedUpdateInput>
  /**
   * Choose, which AssessmentResult to update.
   */
  where: Prisma.AssessmentResultWhereUniqueInput
}

/**
 * AssessmentResult updateMany
 */
export type AssessmentResultUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AssessmentResults.
   */
  data: Prisma.XOR<Prisma.AssessmentResultUpdateManyMutationInput, Prisma.AssessmentResultUncheckedUpdateManyInput>
  /**
   * Filter which AssessmentResults to update
   */
  where?: Prisma.AssessmentResultWhereInput
  /**
   * Limit how many AssessmentResults to update.
   */
  limit?: number
}

/**
 * AssessmentResult updateManyAndReturn
 */
export type AssessmentResultUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * The data used to update AssessmentResults.
   */
  data: Prisma.XOR<Prisma.AssessmentResultUpdateManyMutationInput, Prisma.AssessmentResultUncheckedUpdateManyInput>
  /**
   * Filter which AssessmentResults to update
   */
  where?: Prisma.AssessmentResultWhereInput
  /**
   * Limit how many AssessmentResults to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AssessmentResult upsert
 */
export type AssessmentResultUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * The filter to search for the AssessmentResult to update in case it exists.
   */
  where: Prisma.AssessmentResultWhereUniqueInput
  /**
   * In case the AssessmentResult found by the `where` argument doesn't exist, create a new AssessmentResult with this data.
   */
  create: Prisma.XOR<Prisma.AssessmentResultCreateInput, Prisma.AssessmentResultUncheckedCreateInput>
  /**
   * In case the AssessmentResult was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssessmentResultUpdateInput, Prisma.AssessmentResultUncheckedUpdateInput>
}

/**
 * AssessmentResult delete
 */
export type AssessmentResultDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  /**
   * Filter which AssessmentResult to delete.
   */
  where: Prisma.AssessmentResultWhereUniqueInput
}

/**
 * AssessmentResult deleteMany
 */
export type AssessmentResultDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssessmentResults to delete
   */
  where?: Prisma.AssessmentResultWhereInput
  /**
   * Limit how many AssessmentResults to delete.
   */
  limit?: number
}

/**
 * AssessmentResult without action
 */
export type AssessmentResultDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
}
