
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Assessment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Assessment
 * 
 */
export type AssessmentModel = runtime.Types.Result.DefaultSelection<Prisma.$AssessmentPayload>

export type AggregateAssessment = {
  _count: AssessmentCountAggregateOutputType | null
  _min: AssessmentMinAggregateOutputType | null
  _max: AssessmentMaxAggregateOutputType | null
}

export type AssessmentMinAggregateOutputType = {
  id: string | null
  userId: string | null
  targetRole: string | null
  status: $Enums.AssessmentStatus | null
  startedAt: Date | null
  completedAt: Date | null
}

export type AssessmentMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  targetRole: string | null
  status: $Enums.AssessmentStatus | null
  startedAt: Date | null
  completedAt: Date | null
}

export type AssessmentCountAggregateOutputType = {
  id: number
  userId: number
  targetRole: number
  status: number
  startedAt: number
  completedAt: number
  _all: number
}


export type AssessmentMinAggregateInputType = {
  id?: true
  userId?: true
  targetRole?: true
  status?: true
  startedAt?: true
  completedAt?: true
}

export type AssessmentMaxAggregateInputType = {
  id?: true
  userId?: true
  targetRole?: true
  status?: true
  startedAt?: true
  completedAt?: true
}

export type AssessmentCountAggregateInputType = {
  id?: true
  userId?: true
  targetRole?: true
  status?: true
  startedAt?: true
  completedAt?: true
  _all?: true
}

export type AssessmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Assessment to aggregate.
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assessments to fetch.
   */
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssessmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assessments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assessments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Assessments
  **/
  _count?: true | AssessmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssessmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssessmentMaxAggregateInputType
}

export type GetAssessmentAggregateType<T extends AssessmentAggregateArgs> = {
      [P in keyof T & keyof AggregateAssessment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssessment[P]>
    : Prisma.GetScalarType<T[P], AggregateAssessment[P]>
}




export type AssessmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssessmentWhereInput
  orderBy?: Prisma.AssessmentOrderByWithAggregationInput | Prisma.AssessmentOrderByWithAggregationInput[]
  by: Prisma.AssessmentScalarFieldEnum[] | Prisma.AssessmentScalarFieldEnum
  having?: Prisma.AssessmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssessmentCountAggregateInputType | true
  _min?: AssessmentMinAggregateInputType
  _max?: AssessmentMaxAggregateInputType
}

export type AssessmentGroupByOutputType = {
  id: string
  userId: string
  targetRole: string | null
  status: $Enums.AssessmentStatus
  startedAt: Date
  completedAt: Date | null
  _count: AssessmentCountAggregateOutputType | null
  _min: AssessmentMinAggregateOutputType | null
  _max: AssessmentMaxAggregateOutputType | null
}

type GetAssessmentGroupByPayload<T extends AssessmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssessmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssessmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssessmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssessmentGroupByOutputType[P]>
      }
    >
  >



export type AssessmentWhereInput = {
  AND?: Prisma.AssessmentWhereInput | Prisma.AssessmentWhereInput[]
  OR?: Prisma.AssessmentWhereInput[]
  NOT?: Prisma.AssessmentWhereInput | Prisma.AssessmentWhereInput[]
  id?: Prisma.StringFilter<"Assessment"> | string
  userId?: Prisma.StringFilter<"Assessment"> | string
  targetRole?: Prisma.StringNullableFilter<"Assessment"> | string | null
  status?: Prisma.EnumAssessmentStatusFilter<"Assessment"> | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Assessment"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  results?: Prisma.AssessmentResultListRelationFilter
}

export type AssessmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  targetRole?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  results?: Prisma.AssessmentResultOrderByRelationAggregateInput
}

export type AssessmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AssessmentWhereInput | Prisma.AssessmentWhereInput[]
  OR?: Prisma.AssessmentWhereInput[]
  NOT?: Prisma.AssessmentWhereInput | Prisma.AssessmentWhereInput[]
  userId?: Prisma.StringFilter<"Assessment"> | string
  targetRole?: Prisma.StringNullableFilter<"Assessment"> | string | null
  status?: Prisma.EnumAssessmentStatusFilter<"Assessment"> | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Assessment"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  results?: Prisma.AssessmentResultListRelationFilter
}, "id">

export type AssessmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  targetRole?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AssessmentCountOrderByAggregateInput
  _max?: Prisma.AssessmentMaxOrderByAggregateInput
  _min?: Prisma.AssessmentMinOrderByAggregateInput
}

export type AssessmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssessmentScalarWhereWithAggregatesInput | Prisma.AssessmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssessmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssessmentScalarWhereWithAggregatesInput | Prisma.AssessmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Assessment"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Assessment"> | string
  targetRole?: Prisma.StringNullableWithAggregatesFilter<"Assessment"> | string | null
  status?: Prisma.EnumAssessmentStatusWithAggregatesFilter<"Assessment"> | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"Assessment"> | Date | string
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Assessment"> | Date | string | null
}

export type AssessmentCreateInput = {
  id?: string
  targetRole?: string | null
  status?: $Enums.AssessmentStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutAssessmentsInput
  results?: Prisma.AssessmentResultCreateNestedManyWithoutAssessmentInput
}

export type AssessmentUncheckedCreateInput = {
  id?: string
  userId: string
  targetRole?: string | null
  status?: $Enums.AssessmentStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  results?: Prisma.AssessmentResultUncheckedCreateNestedManyWithoutAssessmentInput
}

export type AssessmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutAssessmentsNestedInput
  results?: Prisma.AssessmentResultUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  results?: Prisma.AssessmentResultUncheckedUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentCreateManyInput = {
  id?: string
  userId: string
  targetRole?: string | null
  status?: $Enums.AssessmentStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
}

export type AssessmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AssessmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AssessmentListRelationFilter = {
  every?: Prisma.AssessmentWhereInput
  some?: Prisma.AssessmentWhereInput
  none?: Prisma.AssessmentWhereInput
}

export type AssessmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssessmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  targetRole?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type AssessmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  targetRole?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type AssessmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  targetRole?: Prisma.SortOrder
  status?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type AssessmentScalarRelationFilter = {
  is?: Prisma.AssessmentWhereInput
  isNot?: Prisma.AssessmentWhereInput
}

export type AssessmentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutUserInput, Prisma.AssessmentUncheckedCreateWithoutUserInput> | Prisma.AssessmentCreateWithoutUserInput[] | Prisma.AssessmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutUserInput | Prisma.AssessmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AssessmentCreateManyUserInputEnvelope
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
}

export type AssessmentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutUserInput, Prisma.AssessmentUncheckedCreateWithoutUserInput> | Prisma.AssessmentCreateWithoutUserInput[] | Prisma.AssessmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutUserInput | Prisma.AssessmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AssessmentCreateManyUserInputEnvelope
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
}

export type AssessmentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutUserInput, Prisma.AssessmentUncheckedCreateWithoutUserInput> | Prisma.AssessmentCreateWithoutUserInput[] | Prisma.AssessmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutUserInput | Prisma.AssessmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AssessmentUpsertWithWhereUniqueWithoutUserInput | Prisma.AssessmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AssessmentCreateManyUserInputEnvelope
  set?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  disconnect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  delete?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  update?: Prisma.AssessmentUpdateWithWhereUniqueWithoutUserInput | Prisma.AssessmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AssessmentUpdateManyWithWhereWithoutUserInput | Prisma.AssessmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
}

export type AssessmentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutUserInput, Prisma.AssessmentUncheckedCreateWithoutUserInput> | Prisma.AssessmentCreateWithoutUserInput[] | Prisma.AssessmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutUserInput | Prisma.AssessmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AssessmentUpsertWithWhereUniqueWithoutUserInput | Prisma.AssessmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AssessmentCreateManyUserInputEnvelope
  set?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  disconnect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  delete?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  connect?: Prisma.AssessmentWhereUniqueInput | Prisma.AssessmentWhereUniqueInput[]
  update?: Prisma.AssessmentUpdateWithWhereUniqueWithoutUserInput | Prisma.AssessmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AssessmentUpdateManyWithWhereWithoutUserInput | Prisma.AssessmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
}

export type EnumAssessmentStatusFieldUpdateOperationsInput = {
  set?: $Enums.AssessmentStatus
}

export type AssessmentCreateNestedOneWithoutResultsInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutResultsInput, Prisma.AssessmentUncheckedCreateWithoutResultsInput>
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutResultsInput
  connect?: Prisma.AssessmentWhereUniqueInput
}

export type AssessmentUpdateOneRequiredWithoutResultsNestedInput = {
  create?: Prisma.XOR<Prisma.AssessmentCreateWithoutResultsInput, Prisma.AssessmentUncheckedCreateWithoutResultsInput>
  connectOrCreate?: Prisma.AssessmentCreateOrConnectWithoutResultsInput
  upsert?: Prisma.AssessmentUpsertWithoutResultsInput
  connect?: Prisma.AssessmentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AssessmentUpdateToOneWithWhereWithoutResultsInput, Prisma.AssessmentUpdateWithoutResultsInput>, Prisma.AssessmentUncheckedUpdateWithoutResultsInput>
}

export type AssessmentCreateWithoutUserInput = {
  id?: string
  targetRole?: string | null
  status?: $Enums.AssessmentStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  results?: Prisma.AssessmentResultCreateNestedManyWithoutAssessmentInput
}

export type AssessmentUncheckedCreateWithoutUserInput = {
  id?: string
  targetRole?: string | null
  status?: $Enums.AssessmentStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  results?: Prisma.AssessmentResultUncheckedCreateNestedManyWithoutAssessmentInput
}

export type AssessmentCreateOrConnectWithoutUserInput = {
  where: Prisma.AssessmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutUserInput, Prisma.AssessmentUncheckedCreateWithoutUserInput>
}

export type AssessmentCreateManyUserInputEnvelope = {
  data: Prisma.AssessmentCreateManyUserInput | Prisma.AssessmentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AssessmentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AssessmentWhereUniqueInput
  update: Prisma.XOR<Prisma.AssessmentUpdateWithoutUserInput, Prisma.AssessmentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutUserInput, Prisma.AssessmentUncheckedCreateWithoutUserInput>
}

export type AssessmentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AssessmentWhereUniqueInput
  data: Prisma.XOR<Prisma.AssessmentUpdateWithoutUserInput, Prisma.AssessmentUncheckedUpdateWithoutUserInput>
}

export type AssessmentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AssessmentScalarWhereInput
  data: Prisma.XOR<Prisma.AssessmentUpdateManyMutationInput, Prisma.AssessmentUncheckedUpdateManyWithoutUserInput>
}

export type AssessmentScalarWhereInput = {
  AND?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
  OR?: Prisma.AssessmentScalarWhereInput[]
  NOT?: Prisma.AssessmentScalarWhereInput | Prisma.AssessmentScalarWhereInput[]
  id?: Prisma.StringFilter<"Assessment"> | string
  userId?: Prisma.StringFilter<"Assessment"> | string
  targetRole?: Prisma.StringNullableFilter<"Assessment"> | string | null
  status?: Prisma.EnumAssessmentStatusFilter<"Assessment"> | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFilter<"Assessment"> | Date | string
  completedAt?: Prisma.DateTimeNullableFilter<"Assessment"> | Date | string | null
}

export type AssessmentCreateWithoutResultsInput = {
  id?: string
  targetRole?: string | null
  status?: $Enums.AssessmentStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutAssessmentsInput
}

export type AssessmentUncheckedCreateWithoutResultsInput = {
  id?: string
  userId: string
  targetRole?: string | null
  status?: $Enums.AssessmentStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
}

export type AssessmentCreateOrConnectWithoutResultsInput = {
  where: Prisma.AssessmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutResultsInput, Prisma.AssessmentUncheckedCreateWithoutResultsInput>
}

export type AssessmentUpsertWithoutResultsInput = {
  update: Prisma.XOR<Prisma.AssessmentUpdateWithoutResultsInput, Prisma.AssessmentUncheckedUpdateWithoutResultsInput>
  create: Prisma.XOR<Prisma.AssessmentCreateWithoutResultsInput, Prisma.AssessmentUncheckedCreateWithoutResultsInput>
  where?: Prisma.AssessmentWhereInput
}

export type AssessmentUpdateToOneWithWhereWithoutResultsInput = {
  where?: Prisma.AssessmentWhereInput
  data: Prisma.XOR<Prisma.AssessmentUpdateWithoutResultsInput, Prisma.AssessmentUncheckedUpdateWithoutResultsInput>
}

export type AssessmentUpdateWithoutResultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutAssessmentsNestedInput
}

export type AssessmentUncheckedUpdateWithoutResultsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AssessmentCreateManyUserInput = {
  id?: string
  targetRole?: string | null
  status?: $Enums.AssessmentStatus
  startedAt?: Date | string
  completedAt?: Date | string | null
}

export type AssessmentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  results?: Prisma.AssessmentResultUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  results?: Prisma.AssessmentResultUncheckedUpdateManyWithoutAssessmentNestedInput
}

export type AssessmentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  targetRole?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAssessmentStatusFieldUpdateOperationsInput | $Enums.AssessmentStatus
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type AssessmentCountOutputType
 */

export type AssessmentCountOutputType = {
  results: number
}

export type AssessmentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  results?: boolean | AssessmentCountOutputTypeCountResultsArgs
}

/**
 * AssessmentCountOutputType without action
 */
export type AssessmentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentCountOutputType
   */
  select?: Prisma.AssessmentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AssessmentCountOutputType without action
 */
export type AssessmentCountOutputTypeCountResultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssessmentResultWhereInput
}


export type AssessmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  targetRole?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  results?: boolean | Prisma.Assessment$resultsArgs<ExtArgs>
  _count?: boolean | Prisma.AssessmentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessment"]>

export type AssessmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  targetRole?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessment"]>

export type AssessmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  targetRole?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assessment"]>

export type AssessmentSelectScalar = {
  id?: boolean
  userId?: boolean
  targetRole?: boolean
  status?: boolean
  startedAt?: boolean
  completedAt?: boolean
}

export type AssessmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "targetRole" | "status" | "startedAt" | "completedAt", ExtArgs["result"]["assessment"]>
export type AssessmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  results?: boolean | Prisma.Assessment$resultsArgs<ExtArgs>
  _count?: boolean | Prisma.AssessmentCountOutputTypeDefaultArgs<ExtArgs>
}
export type AssessmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AssessmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AssessmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Assessment"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    results: Prisma.$AssessmentResultPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    targetRole: string | null
    status: $Enums.AssessmentStatus
    startedAt: Date
    completedAt: Date | null
  }, ExtArgs["result"]["assessment"]>
  composites: {}
}

export type AssessmentGetPayload<S extends boolean | null | undefined | AssessmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssessmentPayload, S>

export type AssessmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssessmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssessmentCountAggregateInputType | true
  }

export interface AssessmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Assessment'], meta: { name: 'Assessment' } }
  /**
   * Find zero or one Assessment that matches the filter.
   * @param {AssessmentFindUniqueArgs} args - Arguments to find a Assessment
   * @example
   * // Get one Assessment
   * const assessment = await prisma.assessment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssessmentFindUniqueArgs>(args: Prisma.SelectSubset<T, AssessmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Assessment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssessmentFindUniqueOrThrowArgs} args - Arguments to find a Assessment
   * @example
   * // Get one Assessment
   * const assessment = await prisma.assessment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssessmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssessmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Assessment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentFindFirstArgs} args - Arguments to find a Assessment
   * @example
   * // Get one Assessment
   * const assessment = await prisma.assessment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssessmentFindFirstArgs>(args?: Prisma.SelectSubset<T, AssessmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Assessment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentFindFirstOrThrowArgs} args - Arguments to find a Assessment
   * @example
   * // Get one Assessment
   * const assessment = await prisma.assessment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssessmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssessmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Assessments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Assessments
   * const assessments = await prisma.assessment.findMany()
   * 
   * // Get first 10 Assessments
   * const assessments = await prisma.assessment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assessmentWithIdOnly = await prisma.assessment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AssessmentFindManyArgs>(args?: Prisma.SelectSubset<T, AssessmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Assessment.
   * @param {AssessmentCreateArgs} args - Arguments to create a Assessment.
   * @example
   * // Create one Assessment
   * const Assessment = await prisma.assessment.create({
   *   data: {
   *     // ... data to create a Assessment
   *   }
   * })
   * 
   */
  create<T extends AssessmentCreateArgs>(args: Prisma.SelectSubset<T, AssessmentCreateArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Assessments.
   * @param {AssessmentCreateManyArgs} args - Arguments to create many Assessments.
   * @example
   * // Create many Assessments
   * const assessment = await prisma.assessment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssessmentCreateManyArgs>(args?: Prisma.SelectSubset<T, AssessmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Assessments and returns the data saved in the database.
   * @param {AssessmentCreateManyAndReturnArgs} args - Arguments to create many Assessments.
   * @example
   * // Create many Assessments
   * const assessment = await prisma.assessment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Assessments and only return the `id`
   * const assessmentWithIdOnly = await prisma.assessment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssessmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssessmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Assessment.
   * @param {AssessmentDeleteArgs} args - Arguments to delete one Assessment.
   * @example
   * // Delete one Assessment
   * const Assessment = await prisma.assessment.delete({
   *   where: {
   *     // ... filter to delete one Assessment
   *   }
   * })
   * 
   */
  delete<T extends AssessmentDeleteArgs>(args: Prisma.SelectSubset<T, AssessmentDeleteArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Assessment.
   * @param {AssessmentUpdateArgs} args - Arguments to update one Assessment.
   * @example
   * // Update one Assessment
   * const assessment = await prisma.assessment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssessmentUpdateArgs>(args: Prisma.SelectSubset<T, AssessmentUpdateArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Assessments.
   * @param {AssessmentDeleteManyArgs} args - Arguments to filter Assessments to delete.
   * @example
   * // Delete a few Assessments
   * const { count } = await prisma.assessment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssessmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssessmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assessments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Assessments
   * const assessment = await prisma.assessment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssessmentUpdateManyArgs>(args: Prisma.SelectSubset<T, AssessmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Assessments and returns the data updated in the database.
   * @param {AssessmentUpdateManyAndReturnArgs} args - Arguments to update many Assessments.
   * @example
   * // Update many Assessments
   * const assessment = await prisma.assessment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Assessments and only return the `id`
   * const assessmentWithIdOnly = await prisma.assessment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssessmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssessmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Assessment.
   * @param {AssessmentUpsertArgs} args - Arguments to update or create a Assessment.
   * @example
   * // Update or create a Assessment
   * const assessment = await prisma.assessment.upsert({
   *   create: {
   *     // ... data to create a Assessment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Assessment we want to update
   *   }
   * })
   */
  upsert<T extends AssessmentUpsertArgs>(args: Prisma.SelectSubset<T, AssessmentUpsertArgs<ExtArgs>>): Prisma.Prisma__AssessmentClient<runtime.Types.Result.GetResult<Prisma.$AssessmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Assessments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentCountArgs} args - Arguments to filter Assessments to count.
   * @example
   * // Count the number of Assessments
   * const count = await prisma.assessment.count({
   *   where: {
   *     // ... the filter for the Assessments we want to count
   *   }
   * })
  **/
  count<T extends AssessmentCountArgs>(
    args?: Prisma.Subset<T, AssessmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssessmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Assessment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssessmentAggregateArgs>(args: Prisma.Subset<T, AssessmentAggregateArgs>): Prisma.PrismaPromise<GetAssessmentAggregateType<T>>

  /**
   * Group by Assessment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssessmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssessmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssessmentGroupByArgs['orderBy'] }
      : { orderBy?: AssessmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssessmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssessmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Assessment model
 */
readonly fields: AssessmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Assessment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssessmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  results<T extends Prisma.Assessment$resultsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Assessment$resultsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssessmentResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Assessment model
 */
export interface AssessmentFieldRefs {
  readonly id: Prisma.FieldRef<"Assessment", 'String'>
  readonly userId: Prisma.FieldRef<"Assessment", 'String'>
  readonly targetRole: Prisma.FieldRef<"Assessment", 'String'>
  readonly status: Prisma.FieldRef<"Assessment", 'AssessmentStatus'>
  readonly startedAt: Prisma.FieldRef<"Assessment", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"Assessment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Assessment findUnique
 */
export type AssessmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessment to fetch.
   */
  where: Prisma.AssessmentWhereUniqueInput
}

/**
 * Assessment findUniqueOrThrow
 */
export type AssessmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessment to fetch.
   */
  where: Prisma.AssessmentWhereUniqueInput
}

/**
 * Assessment findFirst
 */
export type AssessmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessment to fetch.
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assessments to fetch.
   */
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assessments.
   */
  cursor?: Prisma.AssessmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assessments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assessments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assessments.
   */
  distinct?: Prisma.AssessmentScalarFieldEnum | Prisma.AssessmentScalarFieldEnum[]
}

/**
 * Assessment findFirstOrThrow
 */
export type AssessmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessment to fetch.
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assessments to fetch.
   */
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Assessments.
   */
  cursor?: Prisma.AssessmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assessments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assessments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Assessments.
   */
  distinct?: Prisma.AssessmentScalarFieldEnum | Prisma.AssessmentScalarFieldEnum[]
}

/**
 * Assessment findMany
 */
export type AssessmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter, which Assessments to fetch.
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Assessments to fetch.
   */
  orderBy?: Prisma.AssessmentOrderByWithRelationInput | Prisma.AssessmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Assessments.
   */
  cursor?: Prisma.AssessmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Assessments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Assessments.
   */
  skip?: number
  distinct?: Prisma.AssessmentScalarFieldEnum | Prisma.AssessmentScalarFieldEnum[]
}

/**
 * Assessment create
 */
export type AssessmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * The data needed to create a Assessment.
   */
  data: Prisma.XOR<Prisma.AssessmentCreateInput, Prisma.AssessmentUncheckedCreateInput>
}

/**
 * Assessment createMany
 */
export type AssessmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Assessments.
   */
  data: Prisma.AssessmentCreateManyInput | Prisma.AssessmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Assessment createManyAndReturn
 */
export type AssessmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * The data used to create many Assessments.
   */
  data: Prisma.AssessmentCreateManyInput | Prisma.AssessmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Assessment update
 */
export type AssessmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * The data needed to update a Assessment.
   */
  data: Prisma.XOR<Prisma.AssessmentUpdateInput, Prisma.AssessmentUncheckedUpdateInput>
  /**
   * Choose, which Assessment to update.
   */
  where: Prisma.AssessmentWhereUniqueInput
}

/**
 * Assessment updateMany
 */
export type AssessmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Assessments.
   */
  data: Prisma.XOR<Prisma.AssessmentUpdateManyMutationInput, Prisma.AssessmentUncheckedUpdateManyInput>
  /**
   * Filter which Assessments to update
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * Limit how many Assessments to update.
   */
  limit?: number
}

/**
 * Assessment updateManyAndReturn
 */
export type AssessmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * The data used to update Assessments.
   */
  data: Prisma.XOR<Prisma.AssessmentUpdateManyMutationInput, Prisma.AssessmentUncheckedUpdateManyInput>
  /**
   * Filter which Assessments to update
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * Limit how many Assessments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Assessment upsert
 */
export type AssessmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * The filter to search for the Assessment to update in case it exists.
   */
  where: Prisma.AssessmentWhereUniqueInput
  /**
   * In case the Assessment found by the `where` argument doesn't exist, create a new Assessment with this data.
   */
  create: Prisma.XOR<Prisma.AssessmentCreateInput, Prisma.AssessmentUncheckedCreateInput>
  /**
   * In case the Assessment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssessmentUpdateInput, Prisma.AssessmentUncheckedUpdateInput>
}

/**
 * Assessment delete
 */
export type AssessmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
  /**
   * Filter which Assessment to delete.
   */
  where: Prisma.AssessmentWhereUniqueInput
}

/**
 * Assessment deleteMany
 */
export type AssessmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Assessments to delete
   */
  where?: Prisma.AssessmentWhereInput
  /**
   * Limit how many Assessments to delete.
   */
  limit?: number
}

/**
 * Assessment.results
 */
export type Assessment$resultsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssessmentResult
   */
  select?: Prisma.AssessmentResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssessmentResult
   */
  omit?: Prisma.AssessmentResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentResultInclude<ExtArgs> | null
  where?: Prisma.AssessmentResultWhereInput
  orderBy?: Prisma.AssessmentResultOrderByWithRelationInput | Prisma.AssessmentResultOrderByWithRelationInput[]
  cursor?: Prisma.AssessmentResultWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AssessmentResultScalarFieldEnum | Prisma.AssessmentResultScalarFieldEnum[]
}

/**
 * Assessment without action
 */
export type AssessmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Assessment
   */
  select?: Prisma.AssessmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Assessment
   */
  omit?: Prisma.AssessmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssessmentInclude<ExtArgs> | null
}
