
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Evidence` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Evidence
 * 
 */
export type EvidenceModel = runtime.Types.Result.DefaultSelection<Prisma.$EvidencePayload>

export type AggregateEvidence = {
  _count: EvidenceCountAggregateOutputType | null
  _min: EvidenceMinAggregateOutputType | null
  _max: EvidenceMaxAggregateOutputType | null
}

export type EvidenceMinAggregateOutputType = {
  id: string | null
  userId: string | null
  provider: string | null
  referenceUrl: string | null
  rawStored: boolean | null
  retentionUntil: Date | null
  createdAt: Date | null
}

export type EvidenceMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  provider: string | null
  referenceUrl: string | null
  rawStored: boolean | null
  retentionUntil: Date | null
  createdAt: Date | null
}

export type EvidenceCountAggregateOutputType = {
  id: number
  userId: number
  provider: number
  referenceUrl: number
  signals: number
  rawStored: number
  retentionUntil: number
  createdAt: number
  _all: number
}


export type EvidenceMinAggregateInputType = {
  id?: true
  userId?: true
  provider?: true
  referenceUrl?: true
  rawStored?: true
  retentionUntil?: true
  createdAt?: true
}

export type EvidenceMaxAggregateInputType = {
  id?: true
  userId?: true
  provider?: true
  referenceUrl?: true
  rawStored?: true
  retentionUntil?: true
  createdAt?: true
}

export type EvidenceCountAggregateInputType = {
  id?: true
  userId?: true
  provider?: true
  referenceUrl?: true
  signals?: true
  rawStored?: true
  retentionUntil?: true
  createdAt?: true
  _all?: true
}

export type EvidenceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Evidence to aggregate.
   */
  where?: Prisma.EvidenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Evidences to fetch.
   */
  orderBy?: Prisma.EvidenceOrderByWithRelationInput | Prisma.EvidenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EvidenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Evidences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Evidences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Evidences
  **/
  _count?: true | EvidenceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EvidenceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EvidenceMaxAggregateInputType
}

export type GetEvidenceAggregateType<T extends EvidenceAggregateArgs> = {
      [P in keyof T & keyof AggregateEvidence]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEvidence[P]>
    : Prisma.GetScalarType<T[P], AggregateEvidence[P]>
}




export type EvidenceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EvidenceWhereInput
  orderBy?: Prisma.EvidenceOrderByWithAggregationInput | Prisma.EvidenceOrderByWithAggregationInput[]
  by: Prisma.EvidenceScalarFieldEnum[] | Prisma.EvidenceScalarFieldEnum
  having?: Prisma.EvidenceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EvidenceCountAggregateInputType | true
  _min?: EvidenceMinAggregateInputType
  _max?: EvidenceMaxAggregateInputType
}

export type EvidenceGroupByOutputType = {
  id: string
  userId: string
  provider: string | null
  referenceUrl: string | null
  signals: runtime.JsonValue | null
  rawStored: boolean
  retentionUntil: Date | null
  createdAt: Date
  _count: EvidenceCountAggregateOutputType | null
  _min: EvidenceMinAggregateOutputType | null
  _max: EvidenceMaxAggregateOutputType | null
}

type GetEvidenceGroupByPayload<T extends EvidenceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EvidenceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EvidenceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EvidenceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EvidenceGroupByOutputType[P]>
      }
    >
  >



export type EvidenceWhereInput = {
  AND?: Prisma.EvidenceWhereInput | Prisma.EvidenceWhereInput[]
  OR?: Prisma.EvidenceWhereInput[]
  NOT?: Prisma.EvidenceWhereInput | Prisma.EvidenceWhereInput[]
  id?: Prisma.StringFilter<"Evidence"> | string
  userId?: Prisma.StringFilter<"Evidence"> | string
  provider?: Prisma.StringNullableFilter<"Evidence"> | string | null
  referenceUrl?: Prisma.StringNullableFilter<"Evidence"> | string | null
  signals?: Prisma.JsonNullableFilter<"Evidence">
  rawStored?: Prisma.BoolFilter<"Evidence"> | boolean
  retentionUntil?: Prisma.DateTimeNullableFilter<"Evidence"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Evidence"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type EvidenceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrderInput | Prisma.SortOrder
  referenceUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  signals?: Prisma.SortOrderInput | Prisma.SortOrder
  rawStored?: Prisma.SortOrder
  retentionUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type EvidenceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EvidenceWhereInput | Prisma.EvidenceWhereInput[]
  OR?: Prisma.EvidenceWhereInput[]
  NOT?: Prisma.EvidenceWhereInput | Prisma.EvidenceWhereInput[]
  userId?: Prisma.StringFilter<"Evidence"> | string
  provider?: Prisma.StringNullableFilter<"Evidence"> | string | null
  referenceUrl?: Prisma.StringNullableFilter<"Evidence"> | string | null
  signals?: Prisma.JsonNullableFilter<"Evidence">
  rawStored?: Prisma.BoolFilter<"Evidence"> | boolean
  retentionUntil?: Prisma.DateTimeNullableFilter<"Evidence"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Evidence"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type EvidenceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrderInput | Prisma.SortOrder
  referenceUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  signals?: Prisma.SortOrderInput | Prisma.SortOrder
  rawStored?: Prisma.SortOrder
  retentionUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.EvidenceCountOrderByAggregateInput
  _max?: Prisma.EvidenceMaxOrderByAggregateInput
  _min?: Prisma.EvidenceMinOrderByAggregateInput
}

export type EvidenceScalarWhereWithAggregatesInput = {
  AND?: Prisma.EvidenceScalarWhereWithAggregatesInput | Prisma.EvidenceScalarWhereWithAggregatesInput[]
  OR?: Prisma.EvidenceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EvidenceScalarWhereWithAggregatesInput | Prisma.EvidenceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Evidence"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Evidence"> | string
  provider?: Prisma.StringNullableWithAggregatesFilter<"Evidence"> | string | null
  referenceUrl?: Prisma.StringNullableWithAggregatesFilter<"Evidence"> | string | null
  signals?: Prisma.JsonNullableWithAggregatesFilter<"Evidence">
  rawStored?: Prisma.BoolWithAggregatesFilter<"Evidence"> | boolean
  retentionUntil?: Prisma.DateTimeNullableWithAggregatesFilter<"Evidence"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Evidence"> | Date | string
}

export type EvidenceCreateInput = {
  id?: string
  provider?: string | null
  referenceUrl?: string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: boolean
  retentionUntil?: Date | string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutEvidencesInput
}

export type EvidenceUncheckedCreateInput = {
  id?: string
  userId: string
  provider?: string | null
  referenceUrl?: string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: boolean
  retentionUntil?: Date | string | null
  createdAt?: Date | string
}

export type EvidenceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: Prisma.BoolFieldUpdateOperationsInput | boolean
  retentionUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutEvidencesNestedInput
}

export type EvidenceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: Prisma.BoolFieldUpdateOperationsInput | boolean
  retentionUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EvidenceCreateManyInput = {
  id?: string
  userId: string
  provider?: string | null
  referenceUrl?: string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: boolean
  retentionUntil?: Date | string | null
  createdAt?: Date | string
}

export type EvidenceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: Prisma.BoolFieldUpdateOperationsInput | boolean
  retentionUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EvidenceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: Prisma.BoolFieldUpdateOperationsInput | boolean
  retentionUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EvidenceListRelationFilter = {
  every?: Prisma.EvidenceWhereInput
  some?: Prisma.EvidenceWhereInput
  none?: Prisma.EvidenceWhereInput
}

export type EvidenceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EvidenceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  referenceUrl?: Prisma.SortOrder
  signals?: Prisma.SortOrder
  rawStored?: Prisma.SortOrder
  retentionUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EvidenceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  referenceUrl?: Prisma.SortOrder
  rawStored?: Prisma.SortOrder
  retentionUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EvidenceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  provider?: Prisma.SortOrder
  referenceUrl?: Prisma.SortOrder
  rawStored?: Prisma.SortOrder
  retentionUntil?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EvidenceCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EvidenceCreateWithoutUserInput, Prisma.EvidenceUncheckedCreateWithoutUserInput> | Prisma.EvidenceCreateWithoutUserInput[] | Prisma.EvidenceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EvidenceCreateOrConnectWithoutUserInput | Prisma.EvidenceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EvidenceCreateManyUserInputEnvelope
  connect?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
}

export type EvidenceUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EvidenceCreateWithoutUserInput, Prisma.EvidenceUncheckedCreateWithoutUserInput> | Prisma.EvidenceCreateWithoutUserInput[] | Prisma.EvidenceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EvidenceCreateOrConnectWithoutUserInput | Prisma.EvidenceCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EvidenceCreateManyUserInputEnvelope
  connect?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
}

export type EvidenceUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EvidenceCreateWithoutUserInput, Prisma.EvidenceUncheckedCreateWithoutUserInput> | Prisma.EvidenceCreateWithoutUserInput[] | Prisma.EvidenceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EvidenceCreateOrConnectWithoutUserInput | Prisma.EvidenceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EvidenceUpsertWithWhereUniqueWithoutUserInput | Prisma.EvidenceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EvidenceCreateManyUserInputEnvelope
  set?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
  disconnect?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
  delete?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
  connect?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
  update?: Prisma.EvidenceUpdateWithWhereUniqueWithoutUserInput | Prisma.EvidenceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EvidenceUpdateManyWithWhereWithoutUserInput | Prisma.EvidenceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EvidenceScalarWhereInput | Prisma.EvidenceScalarWhereInput[]
}

export type EvidenceUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EvidenceCreateWithoutUserInput, Prisma.EvidenceUncheckedCreateWithoutUserInput> | Prisma.EvidenceCreateWithoutUserInput[] | Prisma.EvidenceUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EvidenceCreateOrConnectWithoutUserInput | Prisma.EvidenceCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EvidenceUpsertWithWhereUniqueWithoutUserInput | Prisma.EvidenceUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EvidenceCreateManyUserInputEnvelope
  set?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
  disconnect?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
  delete?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
  connect?: Prisma.EvidenceWhereUniqueInput | Prisma.EvidenceWhereUniqueInput[]
  update?: Prisma.EvidenceUpdateWithWhereUniqueWithoutUserInput | Prisma.EvidenceUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EvidenceUpdateManyWithWhereWithoutUserInput | Prisma.EvidenceUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EvidenceScalarWhereInput | Prisma.EvidenceScalarWhereInput[]
}

export type EvidenceCreateWithoutUserInput = {
  id?: string
  provider?: string | null
  referenceUrl?: string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: boolean
  retentionUntil?: Date | string | null
  createdAt?: Date | string
}

export type EvidenceUncheckedCreateWithoutUserInput = {
  id?: string
  provider?: string | null
  referenceUrl?: string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: boolean
  retentionUntil?: Date | string | null
  createdAt?: Date | string
}

export type EvidenceCreateOrConnectWithoutUserInput = {
  where: Prisma.EvidenceWhereUniqueInput
  create: Prisma.XOR<Prisma.EvidenceCreateWithoutUserInput, Prisma.EvidenceUncheckedCreateWithoutUserInput>
}

export type EvidenceCreateManyUserInputEnvelope = {
  data: Prisma.EvidenceCreateManyUserInput | Prisma.EvidenceCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type EvidenceUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.EvidenceWhereUniqueInput
  update: Prisma.XOR<Prisma.EvidenceUpdateWithoutUserInput, Prisma.EvidenceUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.EvidenceCreateWithoutUserInput, Prisma.EvidenceUncheckedCreateWithoutUserInput>
}

export type EvidenceUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.EvidenceWhereUniqueInput
  data: Prisma.XOR<Prisma.EvidenceUpdateWithoutUserInput, Prisma.EvidenceUncheckedUpdateWithoutUserInput>
}

export type EvidenceUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.EvidenceScalarWhereInput
  data: Prisma.XOR<Prisma.EvidenceUpdateManyMutationInput, Prisma.EvidenceUncheckedUpdateManyWithoutUserInput>
}

export type EvidenceScalarWhereInput = {
  AND?: Prisma.EvidenceScalarWhereInput | Prisma.EvidenceScalarWhereInput[]
  OR?: Prisma.EvidenceScalarWhereInput[]
  NOT?: Prisma.EvidenceScalarWhereInput | Prisma.EvidenceScalarWhereInput[]
  id?: Prisma.StringFilter<"Evidence"> | string
  userId?: Prisma.StringFilter<"Evidence"> | string
  provider?: Prisma.StringNullableFilter<"Evidence"> | string | null
  referenceUrl?: Prisma.StringNullableFilter<"Evidence"> | string | null
  signals?: Prisma.JsonNullableFilter<"Evidence">
  rawStored?: Prisma.BoolFilter<"Evidence"> | boolean
  retentionUntil?: Prisma.DateTimeNullableFilter<"Evidence"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Evidence"> | Date | string
}

export type EvidenceCreateManyUserInput = {
  id?: string
  provider?: string | null
  referenceUrl?: string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: boolean
  retentionUntil?: Date | string | null
  createdAt?: Date | string
}

export type EvidenceUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: Prisma.BoolFieldUpdateOperationsInput | boolean
  retentionUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EvidenceUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: Prisma.BoolFieldUpdateOperationsInput | boolean
  retentionUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EvidenceUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  provider?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  referenceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  signals?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  rawStored?: Prisma.BoolFieldUpdateOperationsInput | boolean
  retentionUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EvidenceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  provider?: boolean
  referenceUrl?: boolean
  signals?: boolean
  rawStored?: boolean
  retentionUntil?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["evidence"]>

export type EvidenceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  provider?: boolean
  referenceUrl?: boolean
  signals?: boolean
  rawStored?: boolean
  retentionUntil?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["evidence"]>

export type EvidenceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  provider?: boolean
  referenceUrl?: boolean
  signals?: boolean
  rawStored?: boolean
  retentionUntil?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["evidence"]>

export type EvidenceSelectScalar = {
  id?: boolean
  userId?: boolean
  provider?: boolean
  referenceUrl?: boolean
  signals?: boolean
  rawStored?: boolean
  retentionUntil?: boolean
  createdAt?: boolean
}

export type EvidenceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "provider" | "referenceUrl" | "signals" | "rawStored" | "retentionUntil" | "createdAt", ExtArgs["result"]["evidence"]>
export type EvidenceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type EvidenceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type EvidenceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $EvidencePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Evidence"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    provider: string | null
    referenceUrl: string | null
    signals: runtime.JsonValue | null
    rawStored: boolean
    retentionUntil: Date | null
    createdAt: Date
  }, ExtArgs["result"]["evidence"]>
  composites: {}
}

export type EvidenceGetPayload<S extends boolean | null | undefined | EvidenceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EvidencePayload, S>

export type EvidenceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EvidenceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EvidenceCountAggregateInputType | true
  }

export interface EvidenceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Evidence'], meta: { name: 'Evidence' } }
  /**
   * Find zero or one Evidence that matches the filter.
   * @param {EvidenceFindUniqueArgs} args - Arguments to find a Evidence
   * @example
   * // Get one Evidence
   * const evidence = await prisma.evidence.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EvidenceFindUniqueArgs>(args: Prisma.SelectSubset<T, EvidenceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EvidenceClient<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Evidence that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EvidenceFindUniqueOrThrowArgs} args - Arguments to find a Evidence
   * @example
   * // Get one Evidence
   * const evidence = await prisma.evidence.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EvidenceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EvidenceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EvidenceClient<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Evidence that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvidenceFindFirstArgs} args - Arguments to find a Evidence
   * @example
   * // Get one Evidence
   * const evidence = await prisma.evidence.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EvidenceFindFirstArgs>(args?: Prisma.SelectSubset<T, EvidenceFindFirstArgs<ExtArgs>>): Prisma.Prisma__EvidenceClient<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Evidence that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvidenceFindFirstOrThrowArgs} args - Arguments to find a Evidence
   * @example
   * // Get one Evidence
   * const evidence = await prisma.evidence.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EvidenceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EvidenceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EvidenceClient<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Evidences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvidenceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Evidences
   * const evidences = await prisma.evidence.findMany()
   * 
   * // Get first 10 Evidences
   * const evidences = await prisma.evidence.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const evidenceWithIdOnly = await prisma.evidence.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EvidenceFindManyArgs>(args?: Prisma.SelectSubset<T, EvidenceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Evidence.
   * @param {EvidenceCreateArgs} args - Arguments to create a Evidence.
   * @example
   * // Create one Evidence
   * const Evidence = await prisma.evidence.create({
   *   data: {
   *     // ... data to create a Evidence
   *   }
   * })
   * 
   */
  create<T extends EvidenceCreateArgs>(args: Prisma.SelectSubset<T, EvidenceCreateArgs<ExtArgs>>): Prisma.Prisma__EvidenceClient<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Evidences.
   * @param {EvidenceCreateManyArgs} args - Arguments to create many Evidences.
   * @example
   * // Create many Evidences
   * const evidence = await prisma.evidence.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EvidenceCreateManyArgs>(args?: Prisma.SelectSubset<T, EvidenceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Evidences and returns the data saved in the database.
   * @param {EvidenceCreateManyAndReturnArgs} args - Arguments to create many Evidences.
   * @example
   * // Create many Evidences
   * const evidence = await prisma.evidence.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Evidences and only return the `id`
   * const evidenceWithIdOnly = await prisma.evidence.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EvidenceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EvidenceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Evidence.
   * @param {EvidenceDeleteArgs} args - Arguments to delete one Evidence.
   * @example
   * // Delete one Evidence
   * const Evidence = await prisma.evidence.delete({
   *   where: {
   *     // ... filter to delete one Evidence
   *   }
   * })
   * 
   */
  delete<T extends EvidenceDeleteArgs>(args: Prisma.SelectSubset<T, EvidenceDeleteArgs<ExtArgs>>): Prisma.Prisma__EvidenceClient<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Evidence.
   * @param {EvidenceUpdateArgs} args - Arguments to update one Evidence.
   * @example
   * // Update one Evidence
   * const evidence = await prisma.evidence.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EvidenceUpdateArgs>(args: Prisma.SelectSubset<T, EvidenceUpdateArgs<ExtArgs>>): Prisma.Prisma__EvidenceClient<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Evidences.
   * @param {EvidenceDeleteManyArgs} args - Arguments to filter Evidences to delete.
   * @example
   * // Delete a few Evidences
   * const { count } = await prisma.evidence.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EvidenceDeleteManyArgs>(args?: Prisma.SelectSubset<T, EvidenceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Evidences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvidenceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Evidences
   * const evidence = await prisma.evidence.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EvidenceUpdateManyArgs>(args: Prisma.SelectSubset<T, EvidenceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Evidences and returns the data updated in the database.
   * @param {EvidenceUpdateManyAndReturnArgs} args - Arguments to update many Evidences.
   * @example
   * // Update many Evidences
   * const evidence = await prisma.evidence.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Evidences and only return the `id`
   * const evidenceWithIdOnly = await prisma.evidence.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EvidenceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EvidenceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Evidence.
   * @param {EvidenceUpsertArgs} args - Arguments to update or create a Evidence.
   * @example
   * // Update or create a Evidence
   * const evidence = await prisma.evidence.upsert({
   *   create: {
   *     // ... data to create a Evidence
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Evidence we want to update
   *   }
   * })
   */
  upsert<T extends EvidenceUpsertArgs>(args: Prisma.SelectSubset<T, EvidenceUpsertArgs<ExtArgs>>): Prisma.Prisma__EvidenceClient<runtime.Types.Result.GetResult<Prisma.$EvidencePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Evidences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvidenceCountArgs} args - Arguments to filter Evidences to count.
   * @example
   * // Count the number of Evidences
   * const count = await prisma.evidence.count({
   *   where: {
   *     // ... the filter for the Evidences we want to count
   *   }
   * })
  **/
  count<T extends EvidenceCountArgs>(
    args?: Prisma.Subset<T, EvidenceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EvidenceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Evidence.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvidenceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EvidenceAggregateArgs>(args: Prisma.Subset<T, EvidenceAggregateArgs>): Prisma.PrismaPromise<GetEvidenceAggregateType<T>>

  /**
   * Group by Evidence.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EvidenceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EvidenceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EvidenceGroupByArgs['orderBy'] }
      : { orderBy?: EvidenceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EvidenceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEvidenceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Evidence model
 */
readonly fields: EvidenceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Evidence.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EvidenceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Evidence model
 */
export interface EvidenceFieldRefs {
  readonly id: Prisma.FieldRef<"Evidence", 'String'>
  readonly userId: Prisma.FieldRef<"Evidence", 'String'>
  readonly provider: Prisma.FieldRef<"Evidence", 'String'>
  readonly referenceUrl: Prisma.FieldRef<"Evidence", 'String'>
  readonly signals: Prisma.FieldRef<"Evidence", 'Json'>
  readonly rawStored: Prisma.FieldRef<"Evidence", 'Boolean'>
  readonly retentionUntil: Prisma.FieldRef<"Evidence", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Evidence", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Evidence findUnique
 */
export type EvidenceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * Filter, which Evidence to fetch.
   */
  where: Prisma.EvidenceWhereUniqueInput
}

/**
 * Evidence findUniqueOrThrow
 */
export type EvidenceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * Filter, which Evidence to fetch.
   */
  where: Prisma.EvidenceWhereUniqueInput
}

/**
 * Evidence findFirst
 */
export type EvidenceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * Filter, which Evidence to fetch.
   */
  where?: Prisma.EvidenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Evidences to fetch.
   */
  orderBy?: Prisma.EvidenceOrderByWithRelationInput | Prisma.EvidenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Evidences.
   */
  cursor?: Prisma.EvidenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Evidences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Evidences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Evidences.
   */
  distinct?: Prisma.EvidenceScalarFieldEnum | Prisma.EvidenceScalarFieldEnum[]
}

/**
 * Evidence findFirstOrThrow
 */
export type EvidenceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * Filter, which Evidence to fetch.
   */
  where?: Prisma.EvidenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Evidences to fetch.
   */
  orderBy?: Prisma.EvidenceOrderByWithRelationInput | Prisma.EvidenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Evidences.
   */
  cursor?: Prisma.EvidenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Evidences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Evidences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Evidences.
   */
  distinct?: Prisma.EvidenceScalarFieldEnum | Prisma.EvidenceScalarFieldEnum[]
}

/**
 * Evidence findMany
 */
export type EvidenceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * Filter, which Evidences to fetch.
   */
  where?: Prisma.EvidenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Evidences to fetch.
   */
  orderBy?: Prisma.EvidenceOrderByWithRelationInput | Prisma.EvidenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Evidences.
   */
  cursor?: Prisma.EvidenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Evidences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Evidences.
   */
  skip?: number
  distinct?: Prisma.EvidenceScalarFieldEnum | Prisma.EvidenceScalarFieldEnum[]
}

/**
 * Evidence create
 */
export type EvidenceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * The data needed to create a Evidence.
   */
  data: Prisma.XOR<Prisma.EvidenceCreateInput, Prisma.EvidenceUncheckedCreateInput>
}

/**
 * Evidence createMany
 */
export type EvidenceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Evidences.
   */
  data: Prisma.EvidenceCreateManyInput | Prisma.EvidenceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Evidence createManyAndReturn
 */
export type EvidenceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * The data used to create many Evidences.
   */
  data: Prisma.EvidenceCreateManyInput | Prisma.EvidenceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Evidence update
 */
export type EvidenceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * The data needed to update a Evidence.
   */
  data: Prisma.XOR<Prisma.EvidenceUpdateInput, Prisma.EvidenceUncheckedUpdateInput>
  /**
   * Choose, which Evidence to update.
   */
  where: Prisma.EvidenceWhereUniqueInput
}

/**
 * Evidence updateMany
 */
export type EvidenceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Evidences.
   */
  data: Prisma.XOR<Prisma.EvidenceUpdateManyMutationInput, Prisma.EvidenceUncheckedUpdateManyInput>
  /**
   * Filter which Evidences to update
   */
  where?: Prisma.EvidenceWhereInput
  /**
   * Limit how many Evidences to update.
   */
  limit?: number
}

/**
 * Evidence updateManyAndReturn
 */
export type EvidenceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * The data used to update Evidences.
   */
  data: Prisma.XOR<Prisma.EvidenceUpdateManyMutationInput, Prisma.EvidenceUncheckedUpdateManyInput>
  /**
   * Filter which Evidences to update
   */
  where?: Prisma.EvidenceWhereInput
  /**
   * Limit how many Evidences to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Evidence upsert
 */
export type EvidenceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * The filter to search for the Evidence to update in case it exists.
   */
  where: Prisma.EvidenceWhereUniqueInput
  /**
   * In case the Evidence found by the `where` argument doesn't exist, create a new Evidence with this data.
   */
  create: Prisma.XOR<Prisma.EvidenceCreateInput, Prisma.EvidenceUncheckedCreateInput>
  /**
   * In case the Evidence was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EvidenceUpdateInput, Prisma.EvidenceUncheckedUpdateInput>
}

/**
 * Evidence delete
 */
export type EvidenceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
  /**
   * Filter which Evidence to delete.
   */
  where: Prisma.EvidenceWhereUniqueInput
}

/**
 * Evidence deleteMany
 */
export type EvidenceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Evidences to delete
   */
  where?: Prisma.EvidenceWhereInput
  /**
   * Limit how many Evidences to delete.
   */
  limit?: number
}

/**
 * Evidence without action
 */
export type EvidenceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Evidence
   */
  select?: Prisma.EvidenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Evidence
   */
  omit?: Prisma.EvidenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EvidenceInclude<ExtArgs> | null
}
