
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SkillRelation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SkillRelation
 * 
 */
export type SkillRelationModel = runtime.Types.Result.DefaultSelection<Prisma.$SkillRelationPayload>

export type AggregateSkillRelation = {
  _count: SkillRelationCountAggregateOutputType | null
  _avg: SkillRelationAvgAggregateOutputType | null
  _sum: SkillRelationSumAggregateOutputType | null
  _min: SkillRelationMinAggregateOutputType | null
  _max: SkillRelationMaxAggregateOutputType | null
}

export type SkillRelationAvgAggregateOutputType = {
  strength: number | null
}

export type SkillRelationSumAggregateOutputType = {
  strength: number | null
}

export type SkillRelationMinAggregateOutputType = {
  id: string | null
  fromSkillId: string | null
  toSkillId: string | null
  strength: number | null
  createdAt: Date | null
}

export type SkillRelationMaxAggregateOutputType = {
  id: string | null
  fromSkillId: string | null
  toSkillId: string | null
  strength: number | null
  createdAt: Date | null
}

export type SkillRelationCountAggregateOutputType = {
  id: number
  fromSkillId: number
  toSkillId: number
  strength: number
  createdAt: number
  _all: number
}


export type SkillRelationAvgAggregateInputType = {
  strength?: true
}

export type SkillRelationSumAggregateInputType = {
  strength?: true
}

export type SkillRelationMinAggregateInputType = {
  id?: true
  fromSkillId?: true
  toSkillId?: true
  strength?: true
  createdAt?: true
}

export type SkillRelationMaxAggregateInputType = {
  id?: true
  fromSkillId?: true
  toSkillId?: true
  strength?: true
  createdAt?: true
}

export type SkillRelationCountAggregateInputType = {
  id?: true
  fromSkillId?: true
  toSkillId?: true
  strength?: true
  createdAt?: true
  _all?: true
}

export type SkillRelationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SkillRelation to aggregate.
   */
  where?: Prisma.SkillRelationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillRelations to fetch.
   */
  orderBy?: Prisma.SkillRelationOrderByWithRelationInput | Prisma.SkillRelationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SkillRelationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillRelations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillRelations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SkillRelations
  **/
  _count?: true | SkillRelationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SkillRelationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SkillRelationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SkillRelationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SkillRelationMaxAggregateInputType
}

export type GetSkillRelationAggregateType<T extends SkillRelationAggregateArgs> = {
      [P in keyof T & keyof AggregateSkillRelation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSkillRelation[P]>
    : Prisma.GetScalarType<T[P], AggregateSkillRelation[P]>
}




export type SkillRelationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SkillRelationWhereInput
  orderBy?: Prisma.SkillRelationOrderByWithAggregationInput | Prisma.SkillRelationOrderByWithAggregationInput[]
  by: Prisma.SkillRelationScalarFieldEnum[] | Prisma.SkillRelationScalarFieldEnum
  having?: Prisma.SkillRelationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SkillRelationCountAggregateInputType | true
  _avg?: SkillRelationAvgAggregateInputType
  _sum?: SkillRelationSumAggregateInputType
  _min?: SkillRelationMinAggregateInputType
  _max?: SkillRelationMaxAggregateInputType
}

export type SkillRelationGroupByOutputType = {
  id: string
  fromSkillId: string
  toSkillId: string
  strength: number
  createdAt: Date
  _count: SkillRelationCountAggregateOutputType | null
  _avg: SkillRelationAvgAggregateOutputType | null
  _sum: SkillRelationSumAggregateOutputType | null
  _min: SkillRelationMinAggregateOutputType | null
  _max: SkillRelationMaxAggregateOutputType | null
}

type GetSkillRelationGroupByPayload<T extends SkillRelationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SkillRelationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SkillRelationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SkillRelationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SkillRelationGroupByOutputType[P]>
      }
    >
  >



export type SkillRelationWhereInput = {
  AND?: Prisma.SkillRelationWhereInput | Prisma.SkillRelationWhereInput[]
  OR?: Prisma.SkillRelationWhereInput[]
  NOT?: Prisma.SkillRelationWhereInput | Prisma.SkillRelationWhereInput[]
  id?: Prisma.StringFilter<"SkillRelation"> | string
  fromSkillId?: Prisma.StringFilter<"SkillRelation"> | string
  toSkillId?: Prisma.StringFilter<"SkillRelation"> | string
  strength?: Prisma.FloatFilter<"SkillRelation"> | number
  createdAt?: Prisma.DateTimeFilter<"SkillRelation"> | Date | string
  fromSkill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
  toSkill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}

export type SkillRelationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fromSkillId?: Prisma.SortOrder
  toSkillId?: Prisma.SortOrder
  strength?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  fromSkill?: Prisma.SkillOrderByWithRelationInput
  toSkill?: Prisma.SkillOrderByWithRelationInput
}

export type SkillRelationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  fromSkillId_toSkillId?: Prisma.SkillRelationFromSkillIdToSkillIdCompoundUniqueInput
  AND?: Prisma.SkillRelationWhereInput | Prisma.SkillRelationWhereInput[]
  OR?: Prisma.SkillRelationWhereInput[]
  NOT?: Prisma.SkillRelationWhereInput | Prisma.SkillRelationWhereInput[]
  fromSkillId?: Prisma.StringFilter<"SkillRelation"> | string
  toSkillId?: Prisma.StringFilter<"SkillRelation"> | string
  strength?: Prisma.FloatFilter<"SkillRelation"> | number
  createdAt?: Prisma.DateTimeFilter<"SkillRelation"> | Date | string
  fromSkill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
  toSkill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}, "id" | "fromSkillId_toSkillId">

export type SkillRelationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fromSkillId?: Prisma.SortOrder
  toSkillId?: Prisma.SortOrder
  strength?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SkillRelationCountOrderByAggregateInput
  _avg?: Prisma.SkillRelationAvgOrderByAggregateInput
  _max?: Prisma.SkillRelationMaxOrderByAggregateInput
  _min?: Prisma.SkillRelationMinOrderByAggregateInput
  _sum?: Prisma.SkillRelationSumOrderByAggregateInput
}

export type SkillRelationScalarWhereWithAggregatesInput = {
  AND?: Prisma.SkillRelationScalarWhereWithAggregatesInput | Prisma.SkillRelationScalarWhereWithAggregatesInput[]
  OR?: Prisma.SkillRelationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SkillRelationScalarWhereWithAggregatesInput | Prisma.SkillRelationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SkillRelation"> | string
  fromSkillId?: Prisma.StringWithAggregatesFilter<"SkillRelation"> | string
  toSkillId?: Prisma.StringWithAggregatesFilter<"SkillRelation"> | string
  strength?: Prisma.FloatWithAggregatesFilter<"SkillRelation"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SkillRelation"> | Date | string
}

export type SkillRelationCreateInput = {
  id?: string
  strength?: number
  createdAt?: Date | string
  fromSkill: Prisma.SkillCreateNestedOneWithoutFromRelationsInput
  toSkill: Prisma.SkillCreateNestedOneWithoutToRelationsInput
}

export type SkillRelationUncheckedCreateInput = {
  id?: string
  fromSkillId: string
  toSkillId: string
  strength?: number
  createdAt?: Date | string
}

export type SkillRelationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fromSkill?: Prisma.SkillUpdateOneRequiredWithoutFromRelationsNestedInput
  toSkill?: Prisma.SkillUpdateOneRequiredWithoutToRelationsNestedInput
}

export type SkillRelationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromSkillId?: Prisma.StringFieldUpdateOperationsInput | string
  toSkillId?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SkillRelationCreateManyInput = {
  id?: string
  fromSkillId: string
  toSkillId: string
  strength?: number
  createdAt?: Date | string
}

export type SkillRelationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SkillRelationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromSkillId?: Prisma.StringFieldUpdateOperationsInput | string
  toSkillId?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SkillRelationListRelationFilter = {
  every?: Prisma.SkillRelationWhereInput
  some?: Prisma.SkillRelationWhereInput
  none?: Prisma.SkillRelationWhereInput
}

export type SkillRelationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SkillRelationFromSkillIdToSkillIdCompoundUniqueInput = {
  fromSkillId: string
  toSkillId: string
}

export type SkillRelationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromSkillId?: Prisma.SortOrder
  toSkillId?: Prisma.SortOrder
  strength?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SkillRelationAvgOrderByAggregateInput = {
  strength?: Prisma.SortOrder
}

export type SkillRelationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromSkillId?: Prisma.SortOrder
  toSkillId?: Prisma.SortOrder
  strength?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SkillRelationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fromSkillId?: Prisma.SortOrder
  toSkillId?: Prisma.SortOrder
  strength?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SkillRelationSumOrderByAggregateInput = {
  strength?: Prisma.SortOrder
}

export type SkillRelationCreateNestedManyWithoutFromSkillInput = {
  create?: Prisma.XOR<Prisma.SkillRelationCreateWithoutFromSkillInput, Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput> | Prisma.SkillRelationCreateWithoutFromSkillInput[] | Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput[]
  connectOrCreate?: Prisma.SkillRelationCreateOrConnectWithoutFromSkillInput | Prisma.SkillRelationCreateOrConnectWithoutFromSkillInput[]
  createMany?: Prisma.SkillRelationCreateManyFromSkillInputEnvelope
  connect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
}

export type SkillRelationCreateNestedManyWithoutToSkillInput = {
  create?: Prisma.XOR<Prisma.SkillRelationCreateWithoutToSkillInput, Prisma.SkillRelationUncheckedCreateWithoutToSkillInput> | Prisma.SkillRelationCreateWithoutToSkillInput[] | Prisma.SkillRelationUncheckedCreateWithoutToSkillInput[]
  connectOrCreate?: Prisma.SkillRelationCreateOrConnectWithoutToSkillInput | Prisma.SkillRelationCreateOrConnectWithoutToSkillInput[]
  createMany?: Prisma.SkillRelationCreateManyToSkillInputEnvelope
  connect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
}

export type SkillRelationUncheckedCreateNestedManyWithoutFromSkillInput = {
  create?: Prisma.XOR<Prisma.SkillRelationCreateWithoutFromSkillInput, Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput> | Prisma.SkillRelationCreateWithoutFromSkillInput[] | Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput[]
  connectOrCreate?: Prisma.SkillRelationCreateOrConnectWithoutFromSkillInput | Prisma.SkillRelationCreateOrConnectWithoutFromSkillInput[]
  createMany?: Prisma.SkillRelationCreateManyFromSkillInputEnvelope
  connect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
}

export type SkillRelationUncheckedCreateNestedManyWithoutToSkillInput = {
  create?: Prisma.XOR<Prisma.SkillRelationCreateWithoutToSkillInput, Prisma.SkillRelationUncheckedCreateWithoutToSkillInput> | Prisma.SkillRelationCreateWithoutToSkillInput[] | Prisma.SkillRelationUncheckedCreateWithoutToSkillInput[]
  connectOrCreate?: Prisma.SkillRelationCreateOrConnectWithoutToSkillInput | Prisma.SkillRelationCreateOrConnectWithoutToSkillInput[]
  createMany?: Prisma.SkillRelationCreateManyToSkillInputEnvelope
  connect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
}

export type SkillRelationUpdateManyWithoutFromSkillNestedInput = {
  create?: Prisma.XOR<Prisma.SkillRelationCreateWithoutFromSkillInput, Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput> | Prisma.SkillRelationCreateWithoutFromSkillInput[] | Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput[]
  connectOrCreate?: Prisma.SkillRelationCreateOrConnectWithoutFromSkillInput | Prisma.SkillRelationCreateOrConnectWithoutFromSkillInput[]
  upsert?: Prisma.SkillRelationUpsertWithWhereUniqueWithoutFromSkillInput | Prisma.SkillRelationUpsertWithWhereUniqueWithoutFromSkillInput[]
  createMany?: Prisma.SkillRelationCreateManyFromSkillInputEnvelope
  set?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  disconnect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  delete?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  connect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  update?: Prisma.SkillRelationUpdateWithWhereUniqueWithoutFromSkillInput | Prisma.SkillRelationUpdateWithWhereUniqueWithoutFromSkillInput[]
  updateMany?: Prisma.SkillRelationUpdateManyWithWhereWithoutFromSkillInput | Prisma.SkillRelationUpdateManyWithWhereWithoutFromSkillInput[]
  deleteMany?: Prisma.SkillRelationScalarWhereInput | Prisma.SkillRelationScalarWhereInput[]
}

export type SkillRelationUpdateManyWithoutToSkillNestedInput = {
  create?: Prisma.XOR<Prisma.SkillRelationCreateWithoutToSkillInput, Prisma.SkillRelationUncheckedCreateWithoutToSkillInput> | Prisma.SkillRelationCreateWithoutToSkillInput[] | Prisma.SkillRelationUncheckedCreateWithoutToSkillInput[]
  connectOrCreate?: Prisma.SkillRelationCreateOrConnectWithoutToSkillInput | Prisma.SkillRelationCreateOrConnectWithoutToSkillInput[]
  upsert?: Prisma.SkillRelationUpsertWithWhereUniqueWithoutToSkillInput | Prisma.SkillRelationUpsertWithWhereUniqueWithoutToSkillInput[]
  createMany?: Prisma.SkillRelationCreateManyToSkillInputEnvelope
  set?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  disconnect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  delete?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  connect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  update?: Prisma.SkillRelationUpdateWithWhereUniqueWithoutToSkillInput | Prisma.SkillRelationUpdateWithWhereUniqueWithoutToSkillInput[]
  updateMany?: Prisma.SkillRelationUpdateManyWithWhereWithoutToSkillInput | Prisma.SkillRelationUpdateManyWithWhereWithoutToSkillInput[]
  deleteMany?: Prisma.SkillRelationScalarWhereInput | Prisma.SkillRelationScalarWhereInput[]
}

export type SkillRelationUncheckedUpdateManyWithoutFromSkillNestedInput = {
  create?: Prisma.XOR<Prisma.SkillRelationCreateWithoutFromSkillInput, Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput> | Prisma.SkillRelationCreateWithoutFromSkillInput[] | Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput[]
  connectOrCreate?: Prisma.SkillRelationCreateOrConnectWithoutFromSkillInput | Prisma.SkillRelationCreateOrConnectWithoutFromSkillInput[]
  upsert?: Prisma.SkillRelationUpsertWithWhereUniqueWithoutFromSkillInput | Prisma.SkillRelationUpsertWithWhereUniqueWithoutFromSkillInput[]
  createMany?: Prisma.SkillRelationCreateManyFromSkillInputEnvelope
  set?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  disconnect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  delete?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  connect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  update?: Prisma.SkillRelationUpdateWithWhereUniqueWithoutFromSkillInput | Prisma.SkillRelationUpdateWithWhereUniqueWithoutFromSkillInput[]
  updateMany?: Prisma.SkillRelationUpdateManyWithWhereWithoutFromSkillInput | Prisma.SkillRelationUpdateManyWithWhereWithoutFromSkillInput[]
  deleteMany?: Prisma.SkillRelationScalarWhereInput | Prisma.SkillRelationScalarWhereInput[]
}

export type SkillRelationUncheckedUpdateManyWithoutToSkillNestedInput = {
  create?: Prisma.XOR<Prisma.SkillRelationCreateWithoutToSkillInput, Prisma.SkillRelationUncheckedCreateWithoutToSkillInput> | Prisma.SkillRelationCreateWithoutToSkillInput[] | Prisma.SkillRelationUncheckedCreateWithoutToSkillInput[]
  connectOrCreate?: Prisma.SkillRelationCreateOrConnectWithoutToSkillInput | Prisma.SkillRelationCreateOrConnectWithoutToSkillInput[]
  upsert?: Prisma.SkillRelationUpsertWithWhereUniqueWithoutToSkillInput | Prisma.SkillRelationUpsertWithWhereUniqueWithoutToSkillInput[]
  createMany?: Prisma.SkillRelationCreateManyToSkillInputEnvelope
  set?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  disconnect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  delete?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  connect?: Prisma.SkillRelationWhereUniqueInput | Prisma.SkillRelationWhereUniqueInput[]
  update?: Prisma.SkillRelationUpdateWithWhereUniqueWithoutToSkillInput | Prisma.SkillRelationUpdateWithWhereUniqueWithoutToSkillInput[]
  updateMany?: Prisma.SkillRelationUpdateManyWithWhereWithoutToSkillInput | Prisma.SkillRelationUpdateManyWithWhereWithoutToSkillInput[]
  deleteMany?: Prisma.SkillRelationScalarWhereInput | Prisma.SkillRelationScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SkillRelationCreateWithoutFromSkillInput = {
  id?: string
  strength?: number
  createdAt?: Date | string
  toSkill: Prisma.SkillCreateNestedOneWithoutToRelationsInput
}

export type SkillRelationUncheckedCreateWithoutFromSkillInput = {
  id?: string
  toSkillId: string
  strength?: number
  createdAt?: Date | string
}

export type SkillRelationCreateOrConnectWithoutFromSkillInput = {
  where: Prisma.SkillRelationWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillRelationCreateWithoutFromSkillInput, Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput>
}

export type SkillRelationCreateManyFromSkillInputEnvelope = {
  data: Prisma.SkillRelationCreateManyFromSkillInput | Prisma.SkillRelationCreateManyFromSkillInput[]
  skipDuplicates?: boolean
}

export type SkillRelationCreateWithoutToSkillInput = {
  id?: string
  strength?: number
  createdAt?: Date | string
  fromSkill: Prisma.SkillCreateNestedOneWithoutFromRelationsInput
}

export type SkillRelationUncheckedCreateWithoutToSkillInput = {
  id?: string
  fromSkillId: string
  strength?: number
  createdAt?: Date | string
}

export type SkillRelationCreateOrConnectWithoutToSkillInput = {
  where: Prisma.SkillRelationWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillRelationCreateWithoutToSkillInput, Prisma.SkillRelationUncheckedCreateWithoutToSkillInput>
}

export type SkillRelationCreateManyToSkillInputEnvelope = {
  data: Prisma.SkillRelationCreateManyToSkillInput | Prisma.SkillRelationCreateManyToSkillInput[]
  skipDuplicates?: boolean
}

export type SkillRelationUpsertWithWhereUniqueWithoutFromSkillInput = {
  where: Prisma.SkillRelationWhereUniqueInput
  update: Prisma.XOR<Prisma.SkillRelationUpdateWithoutFromSkillInput, Prisma.SkillRelationUncheckedUpdateWithoutFromSkillInput>
  create: Prisma.XOR<Prisma.SkillRelationCreateWithoutFromSkillInput, Prisma.SkillRelationUncheckedCreateWithoutFromSkillInput>
}

export type SkillRelationUpdateWithWhereUniqueWithoutFromSkillInput = {
  where: Prisma.SkillRelationWhereUniqueInput
  data: Prisma.XOR<Prisma.SkillRelationUpdateWithoutFromSkillInput, Prisma.SkillRelationUncheckedUpdateWithoutFromSkillInput>
}

export type SkillRelationUpdateManyWithWhereWithoutFromSkillInput = {
  where: Prisma.SkillRelationScalarWhereInput
  data: Prisma.XOR<Prisma.SkillRelationUpdateManyMutationInput, Prisma.SkillRelationUncheckedUpdateManyWithoutFromSkillInput>
}

export type SkillRelationScalarWhereInput = {
  AND?: Prisma.SkillRelationScalarWhereInput | Prisma.SkillRelationScalarWhereInput[]
  OR?: Prisma.SkillRelationScalarWhereInput[]
  NOT?: Prisma.SkillRelationScalarWhereInput | Prisma.SkillRelationScalarWhereInput[]
  id?: Prisma.StringFilter<"SkillRelation"> | string
  fromSkillId?: Prisma.StringFilter<"SkillRelation"> | string
  toSkillId?: Prisma.StringFilter<"SkillRelation"> | string
  strength?: Prisma.FloatFilter<"SkillRelation"> | number
  createdAt?: Prisma.DateTimeFilter<"SkillRelation"> | Date | string
}

export type SkillRelationUpsertWithWhereUniqueWithoutToSkillInput = {
  where: Prisma.SkillRelationWhereUniqueInput
  update: Prisma.XOR<Prisma.SkillRelationUpdateWithoutToSkillInput, Prisma.SkillRelationUncheckedUpdateWithoutToSkillInput>
  create: Prisma.XOR<Prisma.SkillRelationCreateWithoutToSkillInput, Prisma.SkillRelationUncheckedCreateWithoutToSkillInput>
}

export type SkillRelationUpdateWithWhereUniqueWithoutToSkillInput = {
  where: Prisma.SkillRelationWhereUniqueInput
  data: Prisma.XOR<Prisma.SkillRelationUpdateWithoutToSkillInput, Prisma.SkillRelationUncheckedUpdateWithoutToSkillInput>
}

export type SkillRelationUpdateManyWithWhereWithoutToSkillInput = {
  where: Prisma.SkillRelationScalarWhereInput
  data: Prisma.XOR<Prisma.SkillRelationUpdateManyMutationInput, Prisma.SkillRelationUncheckedUpdateManyWithoutToSkillInput>
}

export type SkillRelationCreateManyFromSkillInput = {
  id?: string
  toSkillId: string
  strength?: number
  createdAt?: Date | string
}

export type SkillRelationCreateManyToSkillInput = {
  id?: string
  fromSkillId: string
  strength?: number
  createdAt?: Date | string
}

export type SkillRelationUpdateWithoutFromSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  toSkill?: Prisma.SkillUpdateOneRequiredWithoutToRelationsNestedInput
}

export type SkillRelationUncheckedUpdateWithoutFromSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  toSkillId?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SkillRelationUncheckedUpdateManyWithoutFromSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  toSkillId?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SkillRelationUpdateWithoutToSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fromSkill?: Prisma.SkillUpdateOneRequiredWithoutFromRelationsNestedInput
}

export type SkillRelationUncheckedUpdateWithoutToSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromSkillId?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SkillRelationUncheckedUpdateManyWithoutToSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fromSkillId?: Prisma.StringFieldUpdateOperationsInput | string
  strength?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SkillRelationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromSkillId?: boolean
  toSkillId?: boolean
  strength?: boolean
  createdAt?: boolean
  fromSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  toSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["skillRelation"]>

export type SkillRelationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromSkillId?: boolean
  toSkillId?: boolean
  strength?: boolean
  createdAt?: boolean
  fromSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  toSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["skillRelation"]>

export type SkillRelationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fromSkillId?: boolean
  toSkillId?: boolean
  strength?: boolean
  createdAt?: boolean
  fromSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  toSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["skillRelation"]>

export type SkillRelationSelectScalar = {
  id?: boolean
  fromSkillId?: boolean
  toSkillId?: boolean
  strength?: boolean
  createdAt?: boolean
}

export type SkillRelationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fromSkillId" | "toSkillId" | "strength" | "createdAt", ExtArgs["result"]["skillRelation"]>
export type SkillRelationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fromSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  toSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type SkillRelationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fromSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  toSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type SkillRelationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  fromSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
  toSkill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}

export type $SkillRelationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SkillRelation"
  objects: {
    fromSkill: Prisma.$SkillPayload<ExtArgs>
    toSkill: Prisma.$SkillPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fromSkillId: string
    toSkillId: string
    strength: number
    createdAt: Date
  }, ExtArgs["result"]["skillRelation"]>
  composites: {}
}

export type SkillRelationGetPayload<S extends boolean | null | undefined | SkillRelationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload, S>

export type SkillRelationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SkillRelationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SkillRelationCountAggregateInputType | true
  }

export interface SkillRelationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SkillRelation'], meta: { name: 'SkillRelation' } }
  /**
   * Find zero or one SkillRelation that matches the filter.
   * @param {SkillRelationFindUniqueArgs} args - Arguments to find a SkillRelation
   * @example
   * // Get one SkillRelation
   * const skillRelation = await prisma.skillRelation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SkillRelationFindUniqueArgs>(args: Prisma.SelectSubset<T, SkillRelationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SkillRelationClient<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SkillRelation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SkillRelationFindUniqueOrThrowArgs} args - Arguments to find a SkillRelation
   * @example
   * // Get one SkillRelation
   * const skillRelation = await prisma.skillRelation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SkillRelationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SkillRelationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkillRelationClient<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SkillRelation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillRelationFindFirstArgs} args - Arguments to find a SkillRelation
   * @example
   * // Get one SkillRelation
   * const skillRelation = await prisma.skillRelation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SkillRelationFindFirstArgs>(args?: Prisma.SelectSubset<T, SkillRelationFindFirstArgs<ExtArgs>>): Prisma.Prisma__SkillRelationClient<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SkillRelation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillRelationFindFirstOrThrowArgs} args - Arguments to find a SkillRelation
   * @example
   * // Get one SkillRelation
   * const skillRelation = await prisma.skillRelation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SkillRelationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SkillRelationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkillRelationClient<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SkillRelations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillRelationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SkillRelations
   * const skillRelations = await prisma.skillRelation.findMany()
   * 
   * // Get first 10 SkillRelations
   * const skillRelations = await prisma.skillRelation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const skillRelationWithIdOnly = await prisma.skillRelation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SkillRelationFindManyArgs>(args?: Prisma.SelectSubset<T, SkillRelationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SkillRelation.
   * @param {SkillRelationCreateArgs} args - Arguments to create a SkillRelation.
   * @example
   * // Create one SkillRelation
   * const SkillRelation = await prisma.skillRelation.create({
   *   data: {
   *     // ... data to create a SkillRelation
   *   }
   * })
   * 
   */
  create<T extends SkillRelationCreateArgs>(args: Prisma.SelectSubset<T, SkillRelationCreateArgs<ExtArgs>>): Prisma.Prisma__SkillRelationClient<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SkillRelations.
   * @param {SkillRelationCreateManyArgs} args - Arguments to create many SkillRelations.
   * @example
   * // Create many SkillRelations
   * const skillRelation = await prisma.skillRelation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SkillRelationCreateManyArgs>(args?: Prisma.SelectSubset<T, SkillRelationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SkillRelations and returns the data saved in the database.
   * @param {SkillRelationCreateManyAndReturnArgs} args - Arguments to create many SkillRelations.
   * @example
   * // Create many SkillRelations
   * const skillRelation = await prisma.skillRelation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SkillRelations and only return the `id`
   * const skillRelationWithIdOnly = await prisma.skillRelation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SkillRelationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SkillRelationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SkillRelation.
   * @param {SkillRelationDeleteArgs} args - Arguments to delete one SkillRelation.
   * @example
   * // Delete one SkillRelation
   * const SkillRelation = await prisma.skillRelation.delete({
   *   where: {
   *     // ... filter to delete one SkillRelation
   *   }
   * })
   * 
   */
  delete<T extends SkillRelationDeleteArgs>(args: Prisma.SelectSubset<T, SkillRelationDeleteArgs<ExtArgs>>): Prisma.Prisma__SkillRelationClient<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SkillRelation.
   * @param {SkillRelationUpdateArgs} args - Arguments to update one SkillRelation.
   * @example
   * // Update one SkillRelation
   * const skillRelation = await prisma.skillRelation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SkillRelationUpdateArgs>(args: Prisma.SelectSubset<T, SkillRelationUpdateArgs<ExtArgs>>): Prisma.Prisma__SkillRelationClient<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SkillRelations.
   * @param {SkillRelationDeleteManyArgs} args - Arguments to filter SkillRelations to delete.
   * @example
   * // Delete a few SkillRelations
   * const { count } = await prisma.skillRelation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SkillRelationDeleteManyArgs>(args?: Prisma.SelectSubset<T, SkillRelationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SkillRelations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillRelationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SkillRelations
   * const skillRelation = await prisma.skillRelation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SkillRelationUpdateManyArgs>(args: Prisma.SelectSubset<T, SkillRelationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SkillRelations and returns the data updated in the database.
   * @param {SkillRelationUpdateManyAndReturnArgs} args - Arguments to update many SkillRelations.
   * @example
   * // Update many SkillRelations
   * const skillRelation = await prisma.skillRelation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SkillRelations and only return the `id`
   * const skillRelationWithIdOnly = await prisma.skillRelation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SkillRelationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SkillRelationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SkillRelation.
   * @param {SkillRelationUpsertArgs} args - Arguments to update or create a SkillRelation.
   * @example
   * // Update or create a SkillRelation
   * const skillRelation = await prisma.skillRelation.upsert({
   *   create: {
   *     // ... data to create a SkillRelation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SkillRelation we want to update
   *   }
   * })
   */
  upsert<T extends SkillRelationUpsertArgs>(args: Prisma.SelectSubset<T, SkillRelationUpsertArgs<ExtArgs>>): Prisma.Prisma__SkillRelationClient<runtime.Types.Result.GetResult<Prisma.$SkillRelationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SkillRelations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillRelationCountArgs} args - Arguments to filter SkillRelations to count.
   * @example
   * // Count the number of SkillRelations
   * const count = await prisma.skillRelation.count({
   *   where: {
   *     // ... the filter for the SkillRelations we want to count
   *   }
   * })
  **/
  count<T extends SkillRelationCountArgs>(
    args?: Prisma.Subset<T, SkillRelationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SkillRelationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SkillRelation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillRelationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SkillRelationAggregateArgs>(args: Prisma.Subset<T, SkillRelationAggregateArgs>): Prisma.PrismaPromise<GetSkillRelationAggregateType<T>>

  /**
   * Group by SkillRelation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillRelationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SkillRelationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SkillRelationGroupByArgs['orderBy'] }
      : { orderBy?: SkillRelationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SkillRelationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSkillRelationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SkillRelation model
 */
readonly fields: SkillRelationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SkillRelation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SkillRelationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  fromSkill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  toSkill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SkillRelation model
 */
export interface SkillRelationFieldRefs {
  readonly id: Prisma.FieldRef<"SkillRelation", 'String'>
  readonly fromSkillId: Prisma.FieldRef<"SkillRelation", 'String'>
  readonly toSkillId: Prisma.FieldRef<"SkillRelation", 'String'>
  readonly strength: Prisma.FieldRef<"SkillRelation", 'Float'>
  readonly createdAt: Prisma.FieldRef<"SkillRelation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SkillRelation findUnique
 */
export type SkillRelationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * Filter, which SkillRelation to fetch.
   */
  where: Prisma.SkillRelationWhereUniqueInput
}

/**
 * SkillRelation findUniqueOrThrow
 */
export type SkillRelationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * Filter, which SkillRelation to fetch.
   */
  where: Prisma.SkillRelationWhereUniqueInput
}

/**
 * SkillRelation findFirst
 */
export type SkillRelationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * Filter, which SkillRelation to fetch.
   */
  where?: Prisma.SkillRelationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillRelations to fetch.
   */
  orderBy?: Prisma.SkillRelationOrderByWithRelationInput | Prisma.SkillRelationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SkillRelations.
   */
  cursor?: Prisma.SkillRelationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillRelations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillRelations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkillRelations.
   */
  distinct?: Prisma.SkillRelationScalarFieldEnum | Prisma.SkillRelationScalarFieldEnum[]
}

/**
 * SkillRelation findFirstOrThrow
 */
export type SkillRelationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * Filter, which SkillRelation to fetch.
   */
  where?: Prisma.SkillRelationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillRelations to fetch.
   */
  orderBy?: Prisma.SkillRelationOrderByWithRelationInput | Prisma.SkillRelationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SkillRelations.
   */
  cursor?: Prisma.SkillRelationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillRelations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillRelations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SkillRelations.
   */
  distinct?: Prisma.SkillRelationScalarFieldEnum | Prisma.SkillRelationScalarFieldEnum[]
}

/**
 * SkillRelation findMany
 */
export type SkillRelationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * Filter, which SkillRelations to fetch.
   */
  where?: Prisma.SkillRelationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SkillRelations to fetch.
   */
  orderBy?: Prisma.SkillRelationOrderByWithRelationInput | Prisma.SkillRelationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SkillRelations.
   */
  cursor?: Prisma.SkillRelationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SkillRelations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SkillRelations.
   */
  skip?: number
  distinct?: Prisma.SkillRelationScalarFieldEnum | Prisma.SkillRelationScalarFieldEnum[]
}

/**
 * SkillRelation create
 */
export type SkillRelationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * The data needed to create a SkillRelation.
   */
  data: Prisma.XOR<Prisma.SkillRelationCreateInput, Prisma.SkillRelationUncheckedCreateInput>
}

/**
 * SkillRelation createMany
 */
export type SkillRelationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SkillRelations.
   */
  data: Prisma.SkillRelationCreateManyInput | Prisma.SkillRelationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SkillRelation createManyAndReturn
 */
export type SkillRelationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * The data used to create many SkillRelations.
   */
  data: Prisma.SkillRelationCreateManyInput | Prisma.SkillRelationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SkillRelation update
 */
export type SkillRelationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * The data needed to update a SkillRelation.
   */
  data: Prisma.XOR<Prisma.SkillRelationUpdateInput, Prisma.SkillRelationUncheckedUpdateInput>
  /**
   * Choose, which SkillRelation to update.
   */
  where: Prisma.SkillRelationWhereUniqueInput
}

/**
 * SkillRelation updateMany
 */
export type SkillRelationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SkillRelations.
   */
  data: Prisma.XOR<Prisma.SkillRelationUpdateManyMutationInput, Prisma.SkillRelationUncheckedUpdateManyInput>
  /**
   * Filter which SkillRelations to update
   */
  where?: Prisma.SkillRelationWhereInput
  /**
   * Limit how many SkillRelations to update.
   */
  limit?: number
}

/**
 * SkillRelation updateManyAndReturn
 */
export type SkillRelationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * The data used to update SkillRelations.
   */
  data: Prisma.XOR<Prisma.SkillRelationUpdateManyMutationInput, Prisma.SkillRelationUncheckedUpdateManyInput>
  /**
   * Filter which SkillRelations to update
   */
  where?: Prisma.SkillRelationWhereInput
  /**
   * Limit how many SkillRelations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SkillRelation upsert
 */
export type SkillRelationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * The filter to search for the SkillRelation to update in case it exists.
   */
  where: Prisma.SkillRelationWhereUniqueInput
  /**
   * In case the SkillRelation found by the `where` argument doesn't exist, create a new SkillRelation with this data.
   */
  create: Prisma.XOR<Prisma.SkillRelationCreateInput, Prisma.SkillRelationUncheckedCreateInput>
  /**
   * In case the SkillRelation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SkillRelationUpdateInput, Prisma.SkillRelationUncheckedUpdateInput>
}

/**
 * SkillRelation delete
 */
export type SkillRelationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
  /**
   * Filter which SkillRelation to delete.
   */
  where: Prisma.SkillRelationWhereUniqueInput
}

/**
 * SkillRelation deleteMany
 */
export type SkillRelationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SkillRelations to delete
   */
  where?: Prisma.SkillRelationWhereInput
  /**
   * Limit how many SkillRelations to delete.
   */
  limit?: number
}

/**
 * SkillRelation without action
 */
export type SkillRelationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillRelation
   */
  select?: Prisma.SkillRelationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SkillRelation
   */
  omit?: Prisma.SkillRelationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillRelationInclude<ExtArgs> | null
}
